// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTicketsTicketFidParams creates a new GetTicketsTicketFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTicketsTicketFidParams() *GetTicketsTicketFidParams {
	return &GetTicketsTicketFidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTicketsTicketFidParamsWithTimeout creates a new GetTicketsTicketFidParams object
// with the ability to set a timeout on a request.
func NewGetTicketsTicketFidParamsWithTimeout(timeout time.Duration) *GetTicketsTicketFidParams {
	return &GetTicketsTicketFidParams{
		timeout: timeout,
	}
}

// NewGetTicketsTicketFidParamsWithContext creates a new GetTicketsTicketFidParams object
// with the ability to set a context for a request.
func NewGetTicketsTicketFidParamsWithContext(ctx context.Context) *GetTicketsTicketFidParams {
	return &GetTicketsTicketFidParams{
		Context: ctx,
	}
}

// NewGetTicketsTicketFidParamsWithHTTPClient creates a new GetTicketsTicketFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTicketsTicketFidParamsWithHTTPClient(client *http.Client) *GetTicketsTicketFidParams {
	return &GetTicketsTicketFidParams{
		HTTPClient: client,
	}
}

/*
GetTicketsTicketFidParams contains all the parameters to send to the API endpoint

	for the get tickets ticket fid operation.

	Typically these are written to a http.Request.
*/
type GetTicketsTicketFidParams struct {

	/* TicketFid.

	   Ticket FID to use
	*/
	TicketFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tickets ticket fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTicketsTicketFidParams) WithDefaults() *GetTicketsTicketFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tickets ticket fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTicketsTicketFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) WithTimeout(timeout time.Duration) *GetTicketsTicketFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) WithContext(ctx context.Context) *GetTicketsTicketFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) WithHTTPClient(client *http.Client) *GetTicketsTicketFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTicketFid adds the ticketFid to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) WithTicketFid(ticketFid string) *GetTicketsTicketFidParams {
	o.SetTicketFid(ticketFid)
	return o
}

// SetTicketFid adds the ticketFid to the get tickets ticket fid params
func (o *GetTicketsTicketFidParams) SetTicketFid(ticketFid string) {
	o.TicketFid = ticketFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetTicketsTicketFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ticketFid
	if err := r.SetPathParam("ticketFid", o.TicketFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
