// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetSupportChatEnabledReader is a Reader for the GetSupportChatEnabled structure.
type GetSupportChatEnabledReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSupportChatEnabledReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSupportChatEnabledOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetSupportChatEnabledDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSupportChatEnabledOK creates a GetSupportChatEnabledOK with default headers values
func NewGetSupportChatEnabledOK() *GetSupportChatEnabledOK {
	return &GetSupportChatEnabledOK{}
}

/*
GetSupportChatEnabledOK describes a response with status code 200, with default header values.

Chat Enabled
*/
type GetSupportChatEnabledOK struct {
	Payload *GetSupportChatEnabledOKBody
}

// IsSuccess returns true when this get support chat enabled o k response has a 2xx status code
func (o *GetSupportChatEnabledOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get support chat enabled o k response has a 3xx status code
func (o *GetSupportChatEnabledOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get support chat enabled o k response has a 4xx status code
func (o *GetSupportChatEnabledOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get support chat enabled o k response has a 5xx status code
func (o *GetSupportChatEnabledOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get support chat enabled o k response a status code equal to that given
func (o *GetSupportChatEnabledOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get support chat enabled o k response
func (o *GetSupportChatEnabledOK) Code() int {
	return 200
}

func (o *GetSupportChatEnabledOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /support/chatEnabled][%d] getSupportChatEnabledOK %s", 200, payload)
}

func (o *GetSupportChatEnabledOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /support/chatEnabled][%d] getSupportChatEnabledOK %s", 200, payload)
}

func (o *GetSupportChatEnabledOK) GetPayload() *GetSupportChatEnabledOKBody {
	return o.Payload
}

func (o *GetSupportChatEnabledOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetSupportChatEnabledOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSupportChatEnabledDefault creates a GetSupportChatEnabledDefault with default headers values
func NewGetSupportChatEnabledDefault(code int) *GetSupportChatEnabledDefault {
	return &GetSupportChatEnabledDefault{
		_statusCode: code,
	}
}

/*
GetSupportChatEnabledDefault describes a response with status code -1, with default header values.

Error
*/
type GetSupportChatEnabledDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get support chat enabled default response has a 2xx status code
func (o *GetSupportChatEnabledDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get support chat enabled default response has a 3xx status code
func (o *GetSupportChatEnabledDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get support chat enabled default response has a 4xx status code
func (o *GetSupportChatEnabledDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get support chat enabled default response has a 5xx status code
func (o *GetSupportChatEnabledDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get support chat enabled default response a status code equal to that given
func (o *GetSupportChatEnabledDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get support chat enabled default response
func (o *GetSupportChatEnabledDefault) Code() int {
	return o._statusCode
}

func (o *GetSupportChatEnabledDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /support/chatEnabled][%d] GetSupportChatEnabled default %s", o._statusCode, payload)
}

func (o *GetSupportChatEnabledDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /support/chatEnabled][%d] GetSupportChatEnabled default %s", o._statusCode, payload)
}

func (o *GetSupportChatEnabledDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetSupportChatEnabledDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetSupportChatEnabledOKBody get support chat enabled o k body
swagger:model GetSupportChatEnabledOKBody
*/
type GetSupportChatEnabledOKBody struct {
	models.Envelope

	// data
	Data *models.BoolMessage `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetSupportChatEnabledOKBody) UnmarshalJSON(raw []byte) error {
	// GetSupportChatEnabledOKBodyAO0
	var getSupportChatEnabledOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getSupportChatEnabledOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getSupportChatEnabledOKBodyAO0

	// GetSupportChatEnabledOKBodyAO1
	var dataGetSupportChatEnabledOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetSupportChatEnabledOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetSupportChatEnabledOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetSupportChatEnabledOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getSupportChatEnabledOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getSupportChatEnabledOKBodyAO0)
	var dataGetSupportChatEnabledOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}

	dataGetSupportChatEnabledOKBodyAO1.Data = o.Data

	jsonDataGetSupportChatEnabledOKBodyAO1, errGetSupportChatEnabledOKBodyAO1 := swag.WriteJSON(dataGetSupportChatEnabledOKBodyAO1)
	if errGetSupportChatEnabledOKBodyAO1 != nil {
		return nil, errGetSupportChatEnabledOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetSupportChatEnabledOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get support chat enabled o k body
func (o *GetSupportChatEnabledOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSupportChatEnabledOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getSupportChatEnabledOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getSupportChatEnabledOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get support chat enabled o k body based on the context it is used
func (o *GetSupportChatEnabledOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSupportChatEnabledOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getSupportChatEnabledOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getSupportChatEnabledOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetSupportChatEnabledOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSupportChatEnabledOKBody) UnmarshalBinary(b []byte) error {
	var res GetSupportChatEnabledOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
