// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// PostInteractionsTicketReader is a Reader for the PostInteractionsTicket structure.
type PostInteractionsTicketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInteractionsTicketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostInteractionsTicketOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostInteractionsTicketDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostInteractionsTicketOK creates a PostInteractionsTicketOK with default headers values
func NewPostInteractionsTicketOK() *PostInteractionsTicketOK {
	return &PostInteractionsTicketOK{}
}

/*
PostInteractionsTicketOK describes a response with status code 200, with default header values.

Ticket Information
*/
type PostInteractionsTicketOK struct {
	Payload *PostInteractionsTicketOKBody
}

// IsSuccess returns true when this post interactions ticket o k response has a 2xx status code
func (o *PostInteractionsTicketOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post interactions ticket o k response has a 3xx status code
func (o *PostInteractionsTicketOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post interactions ticket o k response has a 4xx status code
func (o *PostInteractionsTicketOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post interactions ticket o k response has a 5xx status code
func (o *PostInteractionsTicketOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post interactions ticket o k response a status code equal to that given
func (o *PostInteractionsTicketOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post interactions ticket o k response
func (o *PostInteractionsTicketOK) Code() int {
	return 200
}

func (o *PostInteractionsTicketOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /interactions/ticket][%d] postInteractionsTicketOK %s", 200, payload)
}

func (o *PostInteractionsTicketOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /interactions/ticket][%d] postInteractionsTicketOK %s", 200, payload)
}

func (o *PostInteractionsTicketOK) GetPayload() *PostInteractionsTicketOKBody {
	return o.Payload
}

func (o *PostInteractionsTicketOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostInteractionsTicketOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostInteractionsTicketDefault creates a PostInteractionsTicketDefault with default headers values
func NewPostInteractionsTicketDefault(code int) *PostInteractionsTicketDefault {
	return &PostInteractionsTicketDefault{
		_statusCode: code,
	}
}

/*
PostInteractionsTicketDefault describes a response with status code -1, with default header values.

Error
*/
type PostInteractionsTicketDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this post interactions ticket default response has a 2xx status code
func (o *PostInteractionsTicketDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post interactions ticket default response has a 3xx status code
func (o *PostInteractionsTicketDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post interactions ticket default response has a 4xx status code
func (o *PostInteractionsTicketDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post interactions ticket default response has a 5xx status code
func (o *PostInteractionsTicketDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post interactions ticket default response a status code equal to that given
func (o *PostInteractionsTicketDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post interactions ticket default response
func (o *PostInteractionsTicketDefault) Code() int {
	return o._statusCode
}

func (o *PostInteractionsTicketDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /interactions/ticket][%d] PostInteractionsTicket default %s", o._statusCode, payload)
}

func (o *PostInteractionsTicketDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /interactions/ticket][%d] PostInteractionsTicket default %s", o._statusCode, payload)
}

func (o *PostInteractionsTicketDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PostInteractionsTicketDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
PostInteractionsTicketOKBody post interactions ticket o k body
swagger:model PostInteractionsTicketOKBody
*/
type PostInteractionsTicketOKBody struct {
	models.Envelope

	// data
	Data *models.BoolMessage `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostInteractionsTicketOKBody) UnmarshalJSON(raw []byte) error {
	// PostInteractionsTicketOKBodyAO0
	var postInteractionsTicketOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &postInteractionsTicketOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = postInteractionsTicketOKBodyAO0

	// PostInteractionsTicketOKBodyAO1
	var dataPostInteractionsTicketOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPostInteractionsTicketOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataPostInteractionsTicketOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostInteractionsTicketOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	postInteractionsTicketOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postInteractionsTicketOKBodyAO0)
	var dataPostInteractionsTicketOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}

	dataPostInteractionsTicketOKBodyAO1.Data = o.Data

	jsonDataPostInteractionsTicketOKBodyAO1, errPostInteractionsTicketOKBodyAO1 := swag.WriteJSON(dataPostInteractionsTicketOKBodyAO1)
	if errPostInteractionsTicketOKBodyAO1 != nil {
		return nil, errPostInteractionsTicketOKBodyAO1
	}
	_parts = append(_parts, jsonDataPostInteractionsTicketOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post interactions ticket o k body
func (o *PostInteractionsTicketOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostInteractionsTicketOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("postInteractionsTicketOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("postInteractionsTicketOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this post interactions ticket o k body based on the context it is used
func (o *PostInteractionsTicketOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostInteractionsTicketOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("postInteractionsTicketOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("postInteractionsTicketOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostInteractionsTicketOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostInteractionsTicketOKBody) UnmarshalBinary(b []byte) error {
	var res PostInteractionsTicketOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
