// Code generated by go-swagger; DO NOT EDIT.

package customers

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteContactsContactFidPhonesPhoneFidParams creates a new DeleteContactsContactFidPhonesPhoneFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteContactsContactFidPhonesPhoneFidParams() *DeleteContactsContactFidPhonesPhoneFidParams {
	return NewDeleteContactsContactFidPhonesPhoneFidParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteContactsContactFidPhonesPhoneFidParamsWithTimeout creates a new DeleteContactsContactFidPhonesPhoneFidParams object
// with the ability to set a timeout on a request.
func NewDeleteContactsContactFidPhonesPhoneFidParamsWithTimeout(timeout time.Duration) *DeleteContactsContactFidPhonesPhoneFidParams {
	return &DeleteContactsContactFidPhonesPhoneFidParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteContactsContactFidPhonesPhoneFidParamsWithContext creates a new DeleteContactsContactFidPhonesPhoneFidParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteContactsContactFidPhonesPhoneFidParams].
func NewDeleteContactsContactFidPhonesPhoneFidParamsWithContext(ctx context.Context) *DeleteContactsContactFidPhonesPhoneFidParams {
	return &DeleteContactsContactFidPhonesPhoneFidParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteContactsContactFidPhonesPhoneFidParamsWithHTTPClient creates a new DeleteContactsContactFidPhonesPhoneFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteContactsContactFidPhonesPhoneFidParamsWithHTTPClient(client *http.Client) *DeleteContactsContactFidPhonesPhoneFidParams {
	return &DeleteContactsContactFidPhonesPhoneFidParams{
		HTTPClient: client,
	}
}

/*
DeleteContactsContactFidPhonesPhoneFidParams contains all the parameters to send to the API endpoint

	for the delete contacts contact fid phones phone fid operation.

	Typically these are written to a http.Request.
*/
type DeleteContactsContactFidPhonesPhoneFidParams struct {

	/* ContactFid.

	   Contact FID to use
	*/
	ContactFid string

	/* PhoneFid.

	   Phone FID to use
	*/
	PhoneFid string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete contacts contact fid phones phone fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) WithDefaults() *DeleteContactsContactFidPhonesPhoneFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete contacts contact fid phones phone fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) WithTimeout(timeout time.Duration) *DeleteContactsContactFidPhonesPhoneFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete contacts contact fid phones phone fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteContactsContactFidPhonesPhoneFidParams].
func (o *DeleteContactsContactFidPhonesPhoneFidParams) WithContext(ctx context.Context) *DeleteContactsContactFidPhonesPhoneFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete contacts contact fid phones phone fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteContactsContactFidPhonesPhoneFidParams].
func (o *DeleteContactsContactFidPhonesPhoneFidParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) WithHTTPClient(client *http.Client) *DeleteContactsContactFidPhonesPhoneFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContactFid adds the contactFid to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) WithContactFid(contactFid string) *DeleteContactsContactFidPhonesPhoneFidParams {
	o.SetContactFid(contactFid)
	return o
}

// SetContactFid adds the contactFid to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) SetContactFid(contactFid string) {
	o.ContactFid = contactFid
}

// WithPhoneFid adds the phoneFid to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) WithPhoneFid(phoneFid string) *DeleteContactsContactFidPhonesPhoneFidParams {
	o.SetPhoneFid(phoneFid)
	return o
}

// SetPhoneFid adds the phoneFid to the delete contacts contact fid phones phone fid params.
func (o *DeleteContactsContactFidPhonesPhoneFidParams) SetPhoneFid(phoneFid string) {
	o.PhoneFid = phoneFid
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteContactsContactFidPhonesPhoneFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param contactFid
	if err := r.SetPathParam("contactFid", o.ContactFid); err != nil {
		return err
	}

	// path param phoneFid
	if err := r.SetPathParam("phoneFid", o.PhoneFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
