// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// GetCustomersCustomerFidNotificationsReader is a Reader for the GetCustomersCustomerFidNotifications structure.
type GetCustomersCustomerFidNotificationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersCustomerFidNotificationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersCustomerFidNotificationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCustomersCustomerFidNotificationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomersCustomerFidNotificationsOK creates a GetCustomersCustomerFidNotificationsOK with default headers values
func NewGetCustomersCustomerFidNotificationsOK() *GetCustomersCustomerFidNotificationsOK {
	return &GetCustomersCustomerFidNotificationsOK{}
}

/*
GetCustomersCustomerFidNotificationsOK describes a response with status code 200, with default header values.

List of Notifications sent to Customer
*/
type GetCustomersCustomerFidNotificationsOK struct {
	Payload *models.Notifications
}

// IsSuccess returns true when this get customers customer fid notifications o k response has a 2xx status code
func (o *GetCustomersCustomerFidNotificationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers customer fid notifications o k response has a 3xx status code
func (o *GetCustomersCustomerFidNotificationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers customer fid notifications o k response has a 4xx status code
func (o *GetCustomersCustomerFidNotificationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers customer fid notifications o k response has a 5xx status code
func (o *GetCustomersCustomerFidNotificationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers customer fid notifications o k response a status code equal to that given
func (o *GetCustomersCustomerFidNotificationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get customers customer fid notifications o k response
func (o *GetCustomersCustomerFidNotificationsOK) Code() int {
	return 200
}

func (o *GetCustomersCustomerFidNotificationsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/notifications][%d] getCustomersCustomerFidNotificationsOK %s", 200, payload)
}

func (o *GetCustomersCustomerFidNotificationsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/notifications][%d] getCustomersCustomerFidNotificationsOK %s", 200, payload)
}

func (o *GetCustomersCustomerFidNotificationsOK) GetPayload() *models.Notifications {
	return o.Payload
}

func (o *GetCustomersCustomerFidNotificationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Notifications)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomersCustomerFidNotificationsDefault creates a GetCustomersCustomerFidNotificationsDefault with default headers values
func NewGetCustomersCustomerFidNotificationsDefault(code int) *GetCustomersCustomerFidNotificationsDefault {
	return &GetCustomersCustomerFidNotificationsDefault{
		_statusCode: code,
	}
}

/*
GetCustomersCustomerFidNotificationsDefault describes a response with status code -1, with default header values.

Error
*/
type GetCustomersCustomerFidNotificationsDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get customers customer fid notifications default response has a 2xx status code
func (o *GetCustomersCustomerFidNotificationsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get customers customer fid notifications default response has a 3xx status code
func (o *GetCustomersCustomerFidNotificationsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get customers customer fid notifications default response has a 4xx status code
func (o *GetCustomersCustomerFidNotificationsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get customers customer fid notifications default response has a 5xx status code
func (o *GetCustomersCustomerFidNotificationsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get customers customer fid notifications default response a status code equal to that given
func (o *GetCustomersCustomerFidNotificationsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get customers customer fid notifications default response
func (o *GetCustomersCustomerFidNotificationsDefault) Code() int {
	return o._statusCode
}

func (o *GetCustomersCustomerFidNotificationsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/notifications][%d] GetCustomersCustomerFidNotifications default %s", o._statusCode, payload)
}

func (o *GetCustomersCustomerFidNotificationsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/notifications][%d] GetCustomersCustomerFidNotifications default %s", o._statusCode, payload)
}

func (o *GetCustomersCustomerFidNotificationsDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetCustomersCustomerFidNotificationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
