// Code generated by go-swagger; DO NOT EDIT.

package customers

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetCustomersCustomerFidDefaultAddressReader is a Reader for the GetCustomersCustomerFidDefaultAddress structure.
type GetCustomersCustomerFidDefaultAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersCustomerFidDefaultAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersCustomerFidDefaultAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCustomersCustomerFidDefaultAddressDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomersCustomerFidDefaultAddressOK creates a GetCustomersCustomerFidDefaultAddressOK with default headers values
func NewGetCustomersCustomerFidDefaultAddressOK() *GetCustomersCustomerFidDefaultAddressOK {
	return &GetCustomersCustomerFidDefaultAddressOK{}
}

/*
GetCustomersCustomerFidDefaultAddressOK describes a response with status code 200, with default header values.

Address Fid
*/
type GetCustomersCustomerFidDefaultAddressOK struct {
	Payload *GetCustomersCustomerFidDefaultAddressOKBody
}

// IsSuccess returns true when this get customers customer fid default address o k response has a 2xx status code
func (o *GetCustomersCustomerFidDefaultAddressOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers customer fid default address o k response has a 3xx status code
func (o *GetCustomersCustomerFidDefaultAddressOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers customer fid default address o k response has a 4xx status code
func (o *GetCustomersCustomerFidDefaultAddressOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers customer fid default address o k response has a 5xx status code
func (o *GetCustomersCustomerFidDefaultAddressOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers customer fid default address o k response a status code equal to that given
func (o *GetCustomersCustomerFidDefaultAddressOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get customers customer fid default address o k response
func (o *GetCustomersCustomerFidDefaultAddressOK) Code() int {
	return 200
}

func (o *GetCustomersCustomerFidDefaultAddressOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/defaultAddress][%d] getCustomersCustomerFidDefaultAddressOK %s", 200, payload)
}

func (o *GetCustomersCustomerFidDefaultAddressOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/defaultAddress][%d] getCustomersCustomerFidDefaultAddressOK %s", 200, payload)
}

func (o *GetCustomersCustomerFidDefaultAddressOK) GetPayload() *GetCustomersCustomerFidDefaultAddressOKBody {
	return o.Payload
}

func (o *GetCustomersCustomerFidDefaultAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCustomersCustomerFidDefaultAddressOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersCustomerFidDefaultAddressDefault creates a GetCustomersCustomerFidDefaultAddressDefault with default headers values
func NewGetCustomersCustomerFidDefaultAddressDefault(code int) *GetCustomersCustomerFidDefaultAddressDefault {
	return &GetCustomersCustomerFidDefaultAddressDefault{
		_statusCode: code,
	}
}

/*
GetCustomersCustomerFidDefaultAddressDefault describes a response with status code -1, with default header values.

Error
*/
type GetCustomersCustomerFidDefaultAddressDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get customers customer fid default address default response has a 2xx status code
func (o *GetCustomersCustomerFidDefaultAddressDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get customers customer fid default address default response has a 3xx status code
func (o *GetCustomersCustomerFidDefaultAddressDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get customers customer fid default address default response has a 4xx status code
func (o *GetCustomersCustomerFidDefaultAddressDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get customers customer fid default address default response has a 5xx status code
func (o *GetCustomersCustomerFidDefaultAddressDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get customers customer fid default address default response a status code equal to that given
func (o *GetCustomersCustomerFidDefaultAddressDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get customers customer fid default address default response
func (o *GetCustomersCustomerFidDefaultAddressDefault) Code() int {
	return o._statusCode
}

func (o *GetCustomersCustomerFidDefaultAddressDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/defaultAddress][%d] GetCustomersCustomerFidDefaultAddress default %s", o._statusCode, payload)
}

func (o *GetCustomersCustomerFidDefaultAddressDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/defaultAddress][%d] GetCustomersCustomerFidDefaultAddress default %s", o._statusCode, payload)
}

func (o *GetCustomersCustomerFidDefaultAddressDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetCustomersCustomerFidDefaultAddressDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetCustomersCustomerFidDefaultAddressOKBody get customers customer fid default address o k body
swagger:model GetCustomersCustomerFidDefaultAddressOKBody
*/
type GetCustomersCustomerFidDefaultAddressOKBody struct {
	models.Envelope

	// data
	Data *models.Fid `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetCustomersCustomerFidDefaultAddressOKBody) UnmarshalJSON(raw []byte) error {
	// GetCustomersCustomerFidDefaultAddressOKBodyAO0
	var getCustomersCustomerFidDefaultAddressOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getCustomersCustomerFidDefaultAddressOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getCustomersCustomerFidDefaultAddressOKBodyAO0

	// GetCustomersCustomerFidDefaultAddressOKBodyAO1
	var dataGetCustomersCustomerFidDefaultAddressOKBodyAO1 struct {
		Data *models.Fid `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetCustomersCustomerFidDefaultAddressOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetCustomersCustomerFidDefaultAddressOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetCustomersCustomerFidDefaultAddressOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getCustomersCustomerFidDefaultAddressOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getCustomersCustomerFidDefaultAddressOKBodyAO0)
	var dataGetCustomersCustomerFidDefaultAddressOKBodyAO1 struct {
		Data *models.Fid `json:"data,omitempty"`
	}

	dataGetCustomersCustomerFidDefaultAddressOKBodyAO1.Data = o.Data

	jsonDataGetCustomersCustomerFidDefaultAddressOKBodyAO1, errGetCustomersCustomerFidDefaultAddressOKBodyAO1 := swag.WriteJSON(dataGetCustomersCustomerFidDefaultAddressOKBodyAO1)
	if errGetCustomersCustomerFidDefaultAddressOKBodyAO1 != nil {
		return nil, errGetCustomersCustomerFidDefaultAddressOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetCustomersCustomerFidDefaultAddressOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get customers customer fid default address o k body
func (o *GetCustomersCustomerFidDefaultAddressOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidDefaultAddressOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getCustomersCustomerFidDefaultAddressOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getCustomersCustomerFidDefaultAddressOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this get customers customer fid default address o k body based on the context it is used
func (o *GetCustomersCustomerFidDefaultAddressOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidDefaultAddressOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getCustomersCustomerFidDefaultAddressOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getCustomersCustomerFidDefaultAddressOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomersCustomerFidDefaultAddressOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomersCustomerFidDefaultAddressOKBody) UnmarshalBinary(b []byte) error {
	var res GetCustomersCustomerFidDefaultAddressOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
