// Code generated by go-swagger; DO NOT EDIT.

package customers

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCustomersCustomerFidTicketsParams creates a new GetCustomersCustomerFidTicketsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomersCustomerFidTicketsParams() *GetCustomersCustomerFidTicketsParams {
	return NewGetCustomersCustomerFidTicketsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCustomersCustomerFidTicketsParamsWithTimeout creates a new GetCustomersCustomerFidTicketsParams object
// with the ability to set a timeout on a request.
func NewGetCustomersCustomerFidTicketsParamsWithTimeout(timeout time.Duration) *GetCustomersCustomerFidTicketsParams {
	return &GetCustomersCustomerFidTicketsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCustomersCustomerFidTicketsParamsWithContext creates a new GetCustomersCustomerFidTicketsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCustomersCustomerFidTicketsParams].
func NewGetCustomersCustomerFidTicketsParamsWithContext(ctx context.Context) *GetCustomersCustomerFidTicketsParams {
	return &GetCustomersCustomerFidTicketsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCustomersCustomerFidTicketsParamsWithHTTPClient creates a new GetCustomersCustomerFidTicketsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomersCustomerFidTicketsParamsWithHTTPClient(client *http.Client) *GetCustomersCustomerFidTicketsParams {
	return &GetCustomersCustomerFidTicketsParams{
		HTTPClient: client,
	}
}

/*
GetCustomersCustomerFidTicketsParams contains all the parameters to send to the API endpoint

	for the get customers customer fid tickets operation.

	Typically these are written to a http.Request.
*/
type GetCustomersCustomerFidTicketsParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	/* Limit.

	   Maximum number of records per page (default: 20)
	*/
	Limit *int64

	/* Page.

	   Page number (default: 1)
	*/
	Page *int64

	/* SortBy.

	   Sort the tickets by a specific field (default: dateCreated)
	*/
	SortBy *string

	/* SortDirection.

	   Sort the tickets in a specific order (default: ASC)
	*/
	SortDirection *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get customers customer fid tickets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidTicketsParams) WithDefaults() *GetCustomersCustomerFidTicketsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customers customer fid tickets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidTicketsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) WithTimeout(timeout time.Duration) *GetCustomersCustomerFidTicketsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get customers customer fid tickets params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCustomersCustomerFidTicketsParams].
func (o *GetCustomersCustomerFidTicketsParams) WithContext(ctx context.Context) *GetCustomersCustomerFidTicketsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customers customer fid tickets params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCustomersCustomerFidTicketsParams].
func (o *GetCustomersCustomerFidTicketsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) WithHTTPClient(client *http.Client) *GetCustomersCustomerFidTicketsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) WithCustomerFid(customerFid string) *GetCustomersCustomerFidTicketsParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithLimit adds the limit to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) WithLimit(limit *int64) *GetCustomersCustomerFidTicketsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) WithPage(page *int64) *GetCustomersCustomerFidTicketsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) SetPage(page *int64) {
	o.Page = page
}

// WithSortBy adds the sortBy to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) WithSortBy(sortBy *string) *GetCustomersCustomerFidTicketsParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WithSortDirection adds the sortDirection to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) WithSortDirection(sortDirection *string) *GetCustomersCustomerFidTicketsParams {
	o.SetSortDirection(sortDirection)
	return o
}

// SetSortDirection adds the sortDirection to the get customers customer fid tickets params.
func (o *GetCustomersCustomerFidTicketsParams) SetSortDirection(sortDirection *string) {
	o.SortDirection = sortDirection
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCustomersCustomerFidTicketsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := conv.FormatInteger(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.SortBy != nil {

		// query param sortBy
		var qrSortBy string

		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {

			if err := r.SetQueryParam("sortBy", qSortBy); err != nil {
				return err
			}
		}
	}

	if o.SortDirection != nil {

		// query param sortDirection
		var qrSortDirection string

		if o.SortDirection != nil {
			qrSortDirection = *o.SortDirection
		}
		qSortDirection := qrSortDirection
		if qSortDirection != "" {

			if err := r.SetQueryParam("sortDirection", qSortDirection); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
