// Code generated by go-swagger; DO NOT EDIT.

package customers

import (
	"context"
	"net/http"
	"time"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams creates a new PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams() *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	return NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParamsWithTimeout creates a new PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams object
// with the ability to set a timeout on a request.
func NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParamsWithTimeout(timeout time.Duration) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	return &PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParamsWithContext creates a new PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams].
func NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParamsWithContext(ctx context.Context) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	return &PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParamsWithHTTPClient creates a new PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParamsWithHTTPClient(client *http.Client) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	return &PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams{
		HTTPClient: client,
	}
}

/*
PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams contains all the parameters to send to the API endpoint

	for the post customers customer fid subscriptions subscription fid cancel request operation.

	Typically these are written to a http.Request.
*/
type PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	// Payload.
	Payload *models.CreateCancelRequestPayload

	/* SubscriptionFid.

	   Subscription FID to use
	*/
	SubscriptionFid string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post customers customer fid subscriptions subscription fid cancel request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WithDefaults() *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post customers customer fid subscriptions subscription fid cancel request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WithTimeout(timeout time.Duration) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post customers customer fid subscriptions subscription fid cancel request params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams].
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WithContext(ctx context.Context) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post customers customer fid subscriptions subscription fid cancel request params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams].
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WithHTTPClient(client *http.Client) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WithCustomerFid(customerFid string) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithPayload adds the payload to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WithPayload(payload *models.CreateCancelRequestPayload) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) SetPayload(payload *models.CreateCancelRequestPayload) {
	o.Payload = payload
}

// WithSubscriptionFid adds the subscriptionFid to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WithSubscriptionFid(subscriptionFid string) *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams {
	o.SetSubscriptionFid(subscriptionFid)
	return o
}

// SetSubscriptionFid adds the subscriptionFid to the post customers customer fid subscriptions subscription fid cancel request params.
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) SetSubscriptionFid(subscriptionFid string) {
	o.SubscriptionFid = subscriptionFid
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostCustomersCustomerFidSubscriptionsSubscriptionFidCancelRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	// path param subscriptionFid
	if err := r.SetPathParam("subscriptionFid", o.SubscriptionFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
