// Code generated by go-swagger; DO NOT EDIT.

package customers

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams() *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	return NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParamsWithTimeout creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams object
// with the ability to set a timeout on a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParamsWithContext creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams].
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParamsWithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParamsWithHTTPClient creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams{
		HTTPClient: client,
	}
}

/*
PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams contains all the parameters to send to the API endpoint

	for the put customers customer fid subscriptions subscription fid suspend operation.

	Typically these are written to a http.Request.
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	/* SubscriptionFid.

	   Subscription FID to use
	*/
	SubscriptionFid string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put customers customer fid subscriptions subscription fid suspend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) WithDefaults() *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put customers customer fid subscriptions subscription fid suspend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put customers customer fid subscriptions subscription fid suspend params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams].
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) WithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid subscriptions subscription fid suspend params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams].
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) WithSubscriptionFid(subscriptionFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams {
	o.SetSubscriptionFid(subscriptionFid)
	return o
}

// SetSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid suspend params.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) SetSubscriptionFid(subscriptionFid string) {
	o.SubscriptionFid = subscriptionFid
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidSuspendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	// path param subscriptionFid
	if err := r.SetPathParam("subscriptionFid", o.SubscriptionFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
