// Code generated by go-swagger; DO NOT EDIT.

package messenger

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetCustomersCustomerFidContactStatusReader is a Reader for the GetCustomersCustomerFidContactStatus structure.
type GetCustomersCustomerFidContactStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersCustomerFidContactStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersCustomerFidContactStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCustomersCustomerFidContactStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomersCustomerFidContactStatusOK creates a GetCustomersCustomerFidContactStatusOK with default headers values
func NewGetCustomersCustomerFidContactStatusOK() *GetCustomersCustomerFidContactStatusOK {
	return &GetCustomersCustomerFidContactStatusOK{}
}

/*
GetCustomersCustomerFidContactStatusOK describes a response with status code 200, with default header values.

List of Contact Status
*/
type GetCustomersCustomerFidContactStatusOK struct {
	Payload *GetCustomersCustomerFidContactStatusOKBody
}

// IsSuccess returns true when this get customers customer fid contact status o k response has a 2xx status code
func (o *GetCustomersCustomerFidContactStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers customer fid contact status o k response has a 3xx status code
func (o *GetCustomersCustomerFidContactStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers customer fid contact status o k response has a 4xx status code
func (o *GetCustomersCustomerFidContactStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers customer fid contact status o k response has a 5xx status code
func (o *GetCustomersCustomerFidContactStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers customer fid contact status o k response a status code equal to that given
func (o *GetCustomersCustomerFidContactStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get customers customer fid contact status o k response
func (o *GetCustomersCustomerFidContactStatusOK) Code() int {
	return 200
}

func (o *GetCustomersCustomerFidContactStatusOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/contactStatus][%d] getCustomersCustomerFidContactStatusOK %s", 200, payload)
}

func (o *GetCustomersCustomerFidContactStatusOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/contactStatus][%d] getCustomersCustomerFidContactStatusOK %s", 200, payload)
}

func (o *GetCustomersCustomerFidContactStatusOK) GetPayload() *GetCustomersCustomerFidContactStatusOKBody {
	return o.Payload
}

func (o *GetCustomersCustomerFidContactStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCustomersCustomerFidContactStatusOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersCustomerFidContactStatusDefault creates a GetCustomersCustomerFidContactStatusDefault with default headers values
func NewGetCustomersCustomerFidContactStatusDefault(code int) *GetCustomersCustomerFidContactStatusDefault {
	return &GetCustomersCustomerFidContactStatusDefault{
		_statusCode: code,
	}
}

/*
GetCustomersCustomerFidContactStatusDefault describes a response with status code -1, with default header values.

Error
*/
type GetCustomersCustomerFidContactStatusDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get customers customer fid contact status default response has a 2xx status code
func (o *GetCustomersCustomerFidContactStatusDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get customers customer fid contact status default response has a 3xx status code
func (o *GetCustomersCustomerFidContactStatusDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get customers customer fid contact status default response has a 4xx status code
func (o *GetCustomersCustomerFidContactStatusDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get customers customer fid contact status default response has a 5xx status code
func (o *GetCustomersCustomerFidContactStatusDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get customers customer fid contact status default response a status code equal to that given
func (o *GetCustomersCustomerFidContactStatusDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get customers customer fid contact status default response
func (o *GetCustomersCustomerFidContactStatusDefault) Code() int {
	return o._statusCode
}

func (o *GetCustomersCustomerFidContactStatusDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/contactStatus][%d] GetCustomersCustomerFidContactStatus default %s", o._statusCode, payload)
}

func (o *GetCustomersCustomerFidContactStatusDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/{customerFid}/contactStatus][%d] GetCustomersCustomerFidContactStatus default %s", o._statusCode, payload)
}

func (o *GetCustomersCustomerFidContactStatusDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetCustomersCustomerFidContactStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetCustomersCustomerFidContactStatusOKBody get customers customer fid contact status o k body
swagger:model GetCustomersCustomerFidContactStatusOKBody
*/
type GetCustomersCustomerFidContactStatusOKBody struct {
	models.Envelope

	// data
	Data []*models.ContactStatusResponse `json:"data"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetCustomersCustomerFidContactStatusOKBody) UnmarshalJSON(raw []byte) error {
	// GetCustomersCustomerFidContactStatusOKBodyAO0
	var getCustomersCustomerFidContactStatusOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getCustomersCustomerFidContactStatusOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getCustomersCustomerFidContactStatusOKBodyAO0

	// GetCustomersCustomerFidContactStatusOKBodyAO1
	var dataGetCustomersCustomerFidContactStatusOKBodyAO1 struct {
		Data []*models.ContactStatusResponse `json:"data"`
	}
	if err := swag.ReadJSON(raw, &dataGetCustomersCustomerFidContactStatusOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetCustomersCustomerFidContactStatusOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetCustomersCustomerFidContactStatusOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getCustomersCustomerFidContactStatusOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getCustomersCustomerFidContactStatusOKBodyAO0)
	var dataGetCustomersCustomerFidContactStatusOKBodyAO1 struct {
		Data []*models.ContactStatusResponse `json:"data"`
	}

	dataGetCustomersCustomerFidContactStatusOKBodyAO1.Data = o.Data

	jsonDataGetCustomersCustomerFidContactStatusOKBodyAO1, errGetCustomersCustomerFidContactStatusOKBodyAO1 := swag.WriteJSON(dataGetCustomersCustomerFidContactStatusOKBodyAO1)
	if errGetCustomersCustomerFidContactStatusOKBodyAO1 != nil {
		return nil, errGetCustomersCustomerFidContactStatusOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetCustomersCustomerFidContactStatusOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get customers customer fid contact status o k body
func (o *GetCustomersCustomerFidContactStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidContactStatusOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getCustomersCustomerFidContactStatusOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getCustomersCustomerFidContactStatusOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get customers customer fid contact status o k body based on the context it is used
func (o *GetCustomersCustomerFidContactStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidContactStatusOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if swag.IsZero(o.Data[i]) { // not required
				return nil
			}

			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getCustomersCustomerFidContactStatusOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getCustomersCustomerFidContactStatusOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomersCustomerFidContactStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomersCustomerFidContactStatusOKBody) UnmarshalBinary(b []byte) error {
	var res GetCustomersCustomerFidContactStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
