// Code generated by go-swagger; DO NOT EDIT.

package devices

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDeviceDevicesHardwareIDParams creates a new GetDeviceDevicesHardwareIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDeviceDevicesHardwareIDParams() *GetDeviceDevicesHardwareIDParams {
	return NewGetDeviceDevicesHardwareIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetDeviceDevicesHardwareIDParamsWithTimeout creates a new GetDeviceDevicesHardwareIDParams object
// with the ability to set a timeout on a request.
func NewGetDeviceDevicesHardwareIDParamsWithTimeout(timeout time.Duration) *GetDeviceDevicesHardwareIDParams {
	return &GetDeviceDevicesHardwareIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetDeviceDevicesHardwareIDParamsWithContext creates a new GetDeviceDevicesHardwareIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetDeviceDevicesHardwareIDParams].
func NewGetDeviceDevicesHardwareIDParamsWithContext(ctx context.Context) *GetDeviceDevicesHardwareIDParams {
	return &GetDeviceDevicesHardwareIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetDeviceDevicesHardwareIDParamsWithHTTPClient creates a new GetDeviceDevicesHardwareIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDeviceDevicesHardwareIDParamsWithHTTPClient(client *http.Client) *GetDeviceDevicesHardwareIDParams {
	return &GetDeviceDevicesHardwareIDParams{
		HTTPClient: client,
	}
}

/*
GetDeviceDevicesHardwareIDParams contains all the parameters to send to the API endpoint

	for the get device devices hardware ID operation.

	Typically these are written to a http.Request.
*/
type GetDeviceDevicesHardwareIDParams struct {

	/* HardwareID.

	   Hardware ID
	*/
	HardwareID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get device devices hardware ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceDevicesHardwareIDParams) WithDefaults() *GetDeviceDevicesHardwareIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get device devices hardware ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceDevicesHardwareIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get device devices hardware ID params.
func (o *GetDeviceDevicesHardwareIDParams) WithTimeout(timeout time.Duration) *GetDeviceDevicesHardwareIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get device devices hardware ID params.
func (o *GetDeviceDevicesHardwareIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get device devices hardware ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetDeviceDevicesHardwareIDParams].
func (o *GetDeviceDevicesHardwareIDParams) WithContext(ctx context.Context) *GetDeviceDevicesHardwareIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get device devices hardware ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetDeviceDevicesHardwareIDParams].
func (o *GetDeviceDevicesHardwareIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get device devices hardware ID params.
func (o *GetDeviceDevicesHardwareIDParams) WithHTTPClient(client *http.Client) *GetDeviceDevicesHardwareIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get device devices hardware ID params.
func (o *GetDeviceDevicesHardwareIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHardwareID adds the hardwareID to the get device devices hardware ID params.
func (o *GetDeviceDevicesHardwareIDParams) WithHardwareID(hardwareID string) *GetDeviceDevicesHardwareIDParams {
	o.SetHardwareID(hardwareID)
	return o
}

// SetHardwareID adds the hardwareId to the get device devices hardware ID params.
func (o *GetDeviceDevicesHardwareIDParams) SetHardwareID(hardwareID string) {
	o.HardwareID = hardwareID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetDeviceDevicesHardwareIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param hardwareId
	if err := r.SetPathParam("hardwareId", o.HardwareID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
