// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetDeviceStatusesDeviceFidReader is a Reader for the GetDeviceStatusesDeviceFid structure.
type GetDeviceStatusesDeviceFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceStatusesDeviceFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceStatusesDeviceFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDeviceStatusesDeviceFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDeviceStatusesDeviceFidOK creates a GetDeviceStatusesDeviceFidOK with default headers values
func NewGetDeviceStatusesDeviceFidOK() *GetDeviceStatusesDeviceFidOK {
	return &GetDeviceStatusesDeviceFidOK{}
}

/*
GetDeviceStatusesDeviceFidOK describes a response with status code 200, with default header values.

Contact statuses
*/
type GetDeviceStatusesDeviceFidOK struct {
	Payload *GetDeviceStatusesDeviceFidOKBody
}

// IsSuccess returns true when this get device statuses device fid o k response has a 2xx status code
func (o *GetDeviceStatusesDeviceFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get device statuses device fid o k response has a 3xx status code
func (o *GetDeviceStatusesDeviceFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device statuses device fid o k response has a 4xx status code
func (o *GetDeviceStatusesDeviceFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get device statuses device fid o k response has a 5xx status code
func (o *GetDeviceStatusesDeviceFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get device statuses device fid o k response a status code equal to that given
func (o *GetDeviceStatusesDeviceFidOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get device statuses device fid o k response
func (o *GetDeviceStatusesDeviceFidOK) Code() int {
	return 200
}

func (o *GetDeviceStatusesDeviceFidOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/statuses/{deviceFid}][%d] getDeviceStatusesDeviceFidOK %s", 200, payload)
}

func (o *GetDeviceStatusesDeviceFidOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/statuses/{deviceFid}][%d] getDeviceStatusesDeviceFidOK %s", 200, payload)
}

func (o *GetDeviceStatusesDeviceFidOK) GetPayload() *GetDeviceStatusesDeviceFidOKBody {
	return o.Payload
}

func (o *GetDeviceStatusesDeviceFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetDeviceStatusesDeviceFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeviceStatusesDeviceFidDefault creates a GetDeviceStatusesDeviceFidDefault with default headers values
func NewGetDeviceStatusesDeviceFidDefault(code int) *GetDeviceStatusesDeviceFidDefault {
	return &GetDeviceStatusesDeviceFidDefault{
		_statusCode: code,
	}
}

/*
GetDeviceStatusesDeviceFidDefault describes a response with status code -1, with default header values.

Error
*/
type GetDeviceStatusesDeviceFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get device statuses device fid default response has a 2xx status code
func (o *GetDeviceStatusesDeviceFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get device statuses device fid default response has a 3xx status code
func (o *GetDeviceStatusesDeviceFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get device statuses device fid default response has a 4xx status code
func (o *GetDeviceStatusesDeviceFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get device statuses device fid default response has a 5xx status code
func (o *GetDeviceStatusesDeviceFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get device statuses device fid default response a status code equal to that given
func (o *GetDeviceStatusesDeviceFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get device statuses device fid default response
func (o *GetDeviceStatusesDeviceFidDefault) Code() int {
	return o._statusCode
}

func (o *GetDeviceStatusesDeviceFidDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/statuses/{deviceFid}][%d] GetDeviceStatusesDeviceFid default %s", o._statusCode, payload)
}

func (o *GetDeviceStatusesDeviceFidDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /device/statuses/{deviceFid}][%d] GetDeviceStatusesDeviceFid default %s", o._statusCode, payload)
}

func (o *GetDeviceStatusesDeviceFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetDeviceStatusesDeviceFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetDeviceStatusesDeviceFidOKBody get device statuses device fid o k body
swagger:model GetDeviceStatusesDeviceFidOKBody
*/
type GetDeviceStatusesDeviceFidOKBody struct {
	models.Envelope

	// data
	Data *models.ContactStatusesResponse `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetDeviceStatusesDeviceFidOKBody) UnmarshalJSON(raw []byte) error {
	// GetDeviceStatusesDeviceFidOKBodyAO0
	var getDeviceStatusesDeviceFidOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getDeviceStatusesDeviceFidOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getDeviceStatusesDeviceFidOKBodyAO0

	// GetDeviceStatusesDeviceFidOKBodyAO1
	var dataGetDeviceStatusesDeviceFidOKBodyAO1 struct {
		Data *models.ContactStatusesResponse `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetDeviceStatusesDeviceFidOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetDeviceStatusesDeviceFidOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetDeviceStatusesDeviceFidOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getDeviceStatusesDeviceFidOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getDeviceStatusesDeviceFidOKBodyAO0)
	var dataGetDeviceStatusesDeviceFidOKBodyAO1 struct {
		Data *models.ContactStatusesResponse `json:"data,omitempty"`
	}

	dataGetDeviceStatusesDeviceFidOKBodyAO1.Data = o.Data

	jsonDataGetDeviceStatusesDeviceFidOKBodyAO1, errGetDeviceStatusesDeviceFidOKBodyAO1 := swag.WriteJSON(dataGetDeviceStatusesDeviceFidOKBodyAO1)
	if errGetDeviceStatusesDeviceFidOKBodyAO1 != nil {
		return nil, errGetDeviceStatusesDeviceFidOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetDeviceStatusesDeviceFidOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get device statuses device fid o k body
func (o *GetDeviceStatusesDeviceFidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDeviceStatusesDeviceFidOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDeviceStatusesDeviceFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDeviceStatusesDeviceFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get device statuses device fid o k body based on the context it is used
func (o *GetDeviceStatusesDeviceFidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDeviceStatusesDeviceFidOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDeviceStatusesDeviceFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDeviceStatusesDeviceFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetDeviceStatusesDeviceFidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDeviceStatusesDeviceFidOKBody) UnmarshalBinary(b []byte) error {
	var res GetDeviceStatusesDeviceFidOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
