// Code generated by go-swagger; DO NOT EDIT.

package accountant

import (
	"context"
	"net/http"
	"time"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAccountantTransactionsSearchParams creates a new PostAccountantTransactionsSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAccountantTransactionsSearchParams() *PostAccountantTransactionsSearchParams {
	return NewPostAccountantTransactionsSearchParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAccountantTransactionsSearchParamsWithTimeout creates a new PostAccountantTransactionsSearchParams object
// with the ability to set a timeout on a request.
func NewPostAccountantTransactionsSearchParamsWithTimeout(timeout time.Duration) *PostAccountantTransactionsSearchParams {
	return &PostAccountantTransactionsSearchParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAccountantTransactionsSearchParamsWithContext creates a new PostAccountantTransactionsSearchParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAccountantTransactionsSearchParams].
func NewPostAccountantTransactionsSearchParamsWithContext(ctx context.Context) *PostAccountantTransactionsSearchParams {
	return &PostAccountantTransactionsSearchParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAccountantTransactionsSearchParamsWithHTTPClient creates a new PostAccountantTransactionsSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAccountantTransactionsSearchParamsWithHTTPClient(client *http.Client) *PostAccountantTransactionsSearchParams {
	return &PostAccountantTransactionsSearchParams{
		HTTPClient: client,
	}
}

/*
PostAccountantTransactionsSearchParams contains all the parameters to send to the API endpoint

	for the post accountant transactions search operation.

	Typically these are written to a http.Request.
*/
type PostAccountantTransactionsSearchParams struct {

	// Payload.
	Payload *models.FindTransactionsPayload

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post accountant transactions search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccountantTransactionsSearchParams) WithDefaults() *PostAccountantTransactionsSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post accountant transactions search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccountantTransactionsSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post accountant transactions search params.
func (o *PostAccountantTransactionsSearchParams) WithTimeout(timeout time.Duration) *PostAccountantTransactionsSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post accountant transactions search params.
func (o *PostAccountantTransactionsSearchParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post accountant transactions search params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAccountantTransactionsSearchParams].
func (o *PostAccountantTransactionsSearchParams) WithContext(ctx context.Context) *PostAccountantTransactionsSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post accountant transactions search params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAccountantTransactionsSearchParams].
func (o *PostAccountantTransactionsSearchParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post accountant transactions search params.
func (o *PostAccountantTransactionsSearchParams) WithHTTPClient(client *http.Client) *PostAccountantTransactionsSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post accountant transactions search params.
func (o *PostAccountantTransactionsSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the post accountant transactions search params.
func (o *PostAccountantTransactionsSearchParams) WithPayload(payload *models.FindTransactionsPayload) *PostAccountantTransactionsSearchParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post accountant transactions search params.
func (o *PostAccountantTransactionsSearchParams) SetPayload(payload *models.FindTransactionsPayload) {
	o.Payload = payload
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAccountantTransactionsSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
