// Code generated by go-swagger; DO NOT EDIT.

package licence

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new licence API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new licence API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new licence API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for licence API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetLicenceCheck retrieve a licence.
	GetLicenceCheck(params *GetLicenceCheckParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetLicenceCheckOK, error)

	// GetLicenceCheckContext retrieve a licence.
	GetLicenceCheckContext(ctx context.Context, params *GetLicenceCheckParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetLicenceCheckOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
GetLicenceCheckretrieves a licence.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetLicenceCheckContext] instead.
*/
func (a *Client) GetLicenceCheck(params *GetLicenceCheckParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetLicenceCheckOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetLicenceCheckContext(ctx, params, authInfo, opts...)
}

/*
GetLicenceCheckContextretrieves a licence.

Do not use the deprecated [GetLicenceCheckParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetLicenceCheckContext(ctx context.Context, params *GetLicenceCheckParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetLicenceCheckOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetLicenceCheckParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetLicenceCheck",
		Method:             "GET",
		PathPattern:        "/licence/check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetLicenceCheckReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetLicenceCheckOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetLicenceCheckDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [LicenceParams].
	ctx context.Context
}
