// Code generated by go-swagger; DO NOT EDIT.

package finance

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new finance API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new finance API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new finance API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for finance API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetFinancePayments perform a payment search.
	GetFinancePayments(params *GetFinancePaymentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFinancePaymentsOK, error)

	// GetFinancePaymentsContext perform a payment search.
	GetFinancePaymentsContext(ctx context.Context, params *GetFinancePaymentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFinancePaymentsOK, error)

	// GetPublishersPublisherFidFinanceCostImportCostImportFid retrieve the status of cost import.
	GetPublishersPublisherFidFinanceCostImportCostImportFid(params *GetPublishersPublisherFidFinanceCostImportCostImportFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPublishersPublisherFidFinanceCostImportCostImportFidOK, error)

	// GetPublishersPublisherFidFinanceCostImportCostImportFidContext retrieve the status of cost import.
	GetPublishersPublisherFidFinanceCostImportCostImportFidContext(ctx context.Context, params *GetPublishersPublisherFidFinanceCostImportCostImportFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPublishersPublisherFidFinanceCostImportCostImportFidOK, error)

	// PostPublishersPublisherFidFinanceCostImport import cost data.
	PostPublishersPublisherFidFinanceCostImport(params *PostPublishersPublisherFidFinanceCostImportParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostPublishersPublisherFidFinanceCostImportOK, error)

	// PostPublishersPublisherFidFinanceCostImportContext import cost data.
	PostPublishersPublisherFidFinanceCostImportContext(ctx context.Context, params *PostPublishersPublisherFidFinanceCostImportParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostPublishersPublisherFidFinanceCostImportOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
GetFinancePaymentsperforms a payment search.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetFinancePaymentsContext] instead.
*/
func (a *Client) GetFinancePayments(params *GetFinancePaymentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFinancePaymentsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetFinancePaymentsContext(ctx, params, authInfo, opts...)
}

/*
GetFinancePaymentsContextperforms a payment search.

Do not use the deprecated [GetFinancePaymentsParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetFinancePaymentsContext(ctx context.Context, params *GetFinancePaymentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFinancePaymentsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetFinancePaymentsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetFinancePayments",
		Method:             "GET",
		PathPattern:        "/finance/payments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetFinancePaymentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetFinancePaymentsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetFinancePaymentsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetPublishersPublisherFidFinanceCostImportCostImportFidretrieves the status of cost import.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetPublishersPublisherFidFinanceCostImportCostImportFidContext] instead.
*/
func (a *Client) GetPublishersPublisherFidFinanceCostImportCostImportFid(params *GetPublishersPublisherFidFinanceCostImportCostImportFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPublishersPublisherFidFinanceCostImportCostImportFidOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetPublishersPublisherFidFinanceCostImportCostImportFidContext(ctx, params, authInfo, opts...)
}

/*
GetPublishersPublisherFidFinanceCostImportCostImportFidContextretrieves the status of cost import.

Do not use the deprecated [GetPublishersPublisherFidFinanceCostImportCostImportFidParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetPublishersPublisherFidFinanceCostImportCostImportFidContext(ctx context.Context, params *GetPublishersPublisherFidFinanceCostImportCostImportFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPublishersPublisherFidFinanceCostImportCostImportFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetPublishersPublisherFidFinanceCostImportCostImportFidParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetPublishersPublisherFidFinanceCostImportCostImportFid",
		Method:             "GET",
		PathPattern:        "/publishers/{publisherFid}/finance/costImport/{costImportFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetPublishersPublisherFidFinanceCostImportCostImportFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetPublishersPublisherFidFinanceCostImportCostImportFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetPublishersPublisherFidFinanceCostImportCostImportFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostPublishersPublisherFidFinanceCostImportimports cost data.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostPublishersPublisherFidFinanceCostImportContext] instead.
*/
func (a *Client) PostPublishersPublisherFidFinanceCostImport(params *PostPublishersPublisherFidFinanceCostImportParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostPublishersPublisherFidFinanceCostImportOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostPublishersPublisherFidFinanceCostImportContext(ctx, params, authInfo, opts...)
}

/*
PostPublishersPublisherFidFinanceCostImportContextimports cost data.

Do not use the deprecated [PostPublishersPublisherFidFinanceCostImportParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostPublishersPublisherFidFinanceCostImportContext(ctx context.Context, params *PostPublishersPublisherFidFinanceCostImportParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostPublishersPublisherFidFinanceCostImportOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostPublishersPublisherFidFinanceCostImportParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostPublishersPublisherFidFinanceCostImport",
		Method:             "POST",
		PathPattern:        "/publishers/{publisherFid}/finance/costImport",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostPublishersPublisherFidFinanceCostImportReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostPublishersPublisherFidFinanceCostImportOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostPublishersPublisherFidFinanceCostImportDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [FinanceParams].
	ctx context.Context
}
