// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProductsProductFidParams creates a new GetProductsProductFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProductsProductFidParams() *GetProductsProductFidParams {
	return &GetProductsProductFidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsProductFidParamsWithTimeout creates a new GetProductsProductFidParams object
// with the ability to set a timeout on a request.
func NewGetProductsProductFidParamsWithTimeout(timeout time.Duration) *GetProductsProductFidParams {
	return &GetProductsProductFidParams{
		timeout: timeout,
	}
}

// NewGetProductsProductFidParamsWithContext creates a new GetProductsProductFidParams object
// with the ability to set a context for a request.
func NewGetProductsProductFidParamsWithContext(ctx context.Context) *GetProductsProductFidParams {
	return &GetProductsProductFidParams{
		Context: ctx,
	}
}

// NewGetProductsProductFidParamsWithHTTPClient creates a new GetProductsProductFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProductsProductFidParamsWithHTTPClient(client *http.Client) *GetProductsProductFidParams {
	return &GetProductsProductFidParams{
		HTTPClient: client,
	}
}

/*
GetProductsProductFidParams contains all the parameters to send to the API endpoint

	for the get products product fid operation.

	Typically these are written to a http.Request.
*/
type GetProductsProductFidParams struct {

	// ProductFid.
	ProductFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get products product fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsProductFidParams) WithDefaults() *GetProductsProductFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get products product fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsProductFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get products product fid params
func (o *GetProductsProductFidParams) WithTimeout(timeout time.Duration) *GetProductsProductFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products product fid params
func (o *GetProductsProductFidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products product fid params
func (o *GetProductsProductFidParams) WithContext(ctx context.Context) *GetProductsProductFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products product fid params
func (o *GetProductsProductFidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products product fid params
func (o *GetProductsProductFidParams) WithHTTPClient(client *http.Client) *GetProductsProductFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products product fid params
func (o *GetProductsProductFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProductFid adds the productFid to the get products product fid params
func (o *GetProductsProductFidParams) WithProductFid(productFid string) *GetProductsProductFidParams {
	o.SetProductFid(productFid)
	return o
}

// SetProductFid adds the productFid to the get products product fid params
func (o *GetProductsProductFidParams) SetProductFid(productFid string) {
	o.ProductFid = productFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsProductFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param productFid
	if err := r.SetPathParam("productFid", o.ProductFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
