// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetProductsProductFidSkusSkuFidReader is a Reader for the GetProductsProductFidSkusSkuFid structure.
type GetProductsProductFidSkusSkuFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductsProductFidSkusSkuFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProductsProductFidSkusSkuFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProductsProductFidSkusSkuFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProductsProductFidSkusSkuFidOK creates a GetProductsProductFidSkusSkuFidOK with default headers values
func NewGetProductsProductFidSkusSkuFidOK() *GetProductsProductFidSkusSkuFidOK {
	return &GetProductsProductFidSkusSkuFidOK{}
}

/*
GetProductsProductFidSkusSkuFidOK describes a response with status code 200, with default header values.

SKU details
*/
type GetProductsProductFidSkusSkuFidOK struct {
	Payload *GetProductsProductFidSkusSkuFidOKBody
}

// IsSuccess returns true when this get products product fid skus sku fid o k response has a 2xx status code
func (o *GetProductsProductFidSkusSkuFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get products product fid skus sku fid o k response has a 3xx status code
func (o *GetProductsProductFidSkusSkuFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get products product fid skus sku fid o k response has a 4xx status code
func (o *GetProductsProductFidSkusSkuFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get products product fid skus sku fid o k response has a 5xx status code
func (o *GetProductsProductFidSkusSkuFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get products product fid skus sku fid o k response a status code equal to that given
func (o *GetProductsProductFidSkusSkuFidOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get products product fid skus sku fid o k response
func (o *GetProductsProductFidSkusSkuFidOK) Code() int {
	return 200
}

func (o *GetProductsProductFidSkusSkuFidOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/skus/{skuFid}][%d] getProductsProductFidSkusSkuFidOK %s", 200, payload)
}

func (o *GetProductsProductFidSkusSkuFidOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/skus/{skuFid}][%d] getProductsProductFidSkusSkuFidOK %s", 200, payload)
}

func (o *GetProductsProductFidSkusSkuFidOK) GetPayload() *GetProductsProductFidSkusSkuFidOKBody {
	return o.Payload
}

func (o *GetProductsProductFidSkusSkuFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetProductsProductFidSkusSkuFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProductsProductFidSkusSkuFidDefault creates a GetProductsProductFidSkusSkuFidDefault with default headers values
func NewGetProductsProductFidSkusSkuFidDefault(code int) *GetProductsProductFidSkusSkuFidDefault {
	return &GetProductsProductFidSkusSkuFidDefault{
		_statusCode: code,
	}
}

/*
GetProductsProductFidSkusSkuFidDefault describes a response with status code -1, with default header values.

Error
*/
type GetProductsProductFidSkusSkuFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get products product fid skus sku fid default response has a 2xx status code
func (o *GetProductsProductFidSkusSkuFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get products product fid skus sku fid default response has a 3xx status code
func (o *GetProductsProductFidSkusSkuFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get products product fid skus sku fid default response has a 4xx status code
func (o *GetProductsProductFidSkusSkuFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get products product fid skus sku fid default response has a 5xx status code
func (o *GetProductsProductFidSkusSkuFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get products product fid skus sku fid default response a status code equal to that given
func (o *GetProductsProductFidSkusSkuFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get products product fid skus sku fid default response
func (o *GetProductsProductFidSkusSkuFidDefault) Code() int {
	return o._statusCode
}

func (o *GetProductsProductFidSkusSkuFidDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/skus/{skuFid}][%d] GetProductsProductFidSkusSkuFid default %s", o._statusCode, payload)
}

func (o *GetProductsProductFidSkusSkuFidDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/skus/{skuFid}][%d] GetProductsProductFidSkusSkuFid default %s", o._statusCode, payload)
}

func (o *GetProductsProductFidSkusSkuFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetProductsProductFidSkusSkuFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetProductsProductFidSkusSkuFidOKBody get products product fid skus sku fid o k body
swagger:model GetProductsProductFidSkusSkuFidOKBody
*/
type GetProductsProductFidSkusSkuFidOKBody struct {
	models.Envelope

	// data
	Data *models.ProductSku `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetProductsProductFidSkusSkuFidOKBody) UnmarshalJSON(raw []byte) error {
	// GetProductsProductFidSkusSkuFidOKBodyAO0
	var getProductsProductFidSkusSkuFidOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getProductsProductFidSkusSkuFidOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getProductsProductFidSkusSkuFidOKBodyAO0

	// GetProductsProductFidSkusSkuFidOKBodyAO1
	var dataGetProductsProductFidSkusSkuFidOKBodyAO1 struct {
		Data *models.ProductSku `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetProductsProductFidSkusSkuFidOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetProductsProductFidSkusSkuFidOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetProductsProductFidSkusSkuFidOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getProductsProductFidSkusSkuFidOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getProductsProductFidSkusSkuFidOKBodyAO0)
	var dataGetProductsProductFidSkusSkuFidOKBodyAO1 struct {
		Data *models.ProductSku `json:"data,omitempty"`
	}

	dataGetProductsProductFidSkusSkuFidOKBodyAO1.Data = o.Data

	jsonDataGetProductsProductFidSkusSkuFidOKBodyAO1, errGetProductsProductFidSkusSkuFidOKBodyAO1 := swag.WriteJSON(dataGetProductsProductFidSkusSkuFidOKBodyAO1)
	if errGetProductsProductFidSkusSkuFidOKBodyAO1 != nil {
		return nil, errGetProductsProductFidSkusSkuFidOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetProductsProductFidSkusSkuFidOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get products product fid skus sku fid o k body
func (o *GetProductsProductFidSkusSkuFidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetProductsProductFidSkusSkuFidOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getProductsProductFidSkusSkuFidOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getProductsProductFidSkusSkuFidOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this get products product fid skus sku fid o k body based on the context it is used
func (o *GetProductsProductFidSkusSkuFidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetProductsProductFidSkusSkuFidOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getProductsProductFidSkusSkuFidOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getProductsProductFidSkusSkuFidOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetProductsProductFidSkusSkuFidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProductsProductFidSkusSkuFidOKBody) UnmarshalBinary(b []byte) error {
	var res GetProductsProductFidSkusSkuFidOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
