// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetProductsProductFidPricebandsPriceBandFidReader is a Reader for the GetProductsProductFidPricebandsPriceBandFid structure.
type GetProductsProductFidPricebandsPriceBandFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductsProductFidPricebandsPriceBandFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProductsProductFidPricebandsPriceBandFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProductsProductFidPricebandsPriceBandFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProductsProductFidPricebandsPriceBandFidOK creates a GetProductsProductFidPricebandsPriceBandFidOK with default headers values
func NewGetProductsProductFidPricebandsPriceBandFidOK() *GetProductsProductFidPricebandsPriceBandFidOK {
	return &GetProductsProductFidPricebandsPriceBandFidOK{}
}

/*
GetProductsProductFidPricebandsPriceBandFidOK describes a response with status code 200, with default header values.

Price band details
*/
type GetProductsProductFidPricebandsPriceBandFidOK struct {
	Payload *GetProductsProductFidPricebandsPriceBandFidOKBody
}

// IsSuccess returns true when this get products product fid pricebands price band fid o k response has a 2xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get products product fid pricebands price band fid o k response has a 3xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get products product fid pricebands price band fid o k response has a 4xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get products product fid pricebands price band fid o k response has a 5xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get products product fid pricebands price band fid o k response a status code equal to that given
func (o *GetProductsProductFidPricebandsPriceBandFidOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get products product fid pricebands price band fid o k response
func (o *GetProductsProductFidPricebandsPriceBandFidOK) Code() int {
	return 200
}

func (o *GetProductsProductFidPricebandsPriceBandFidOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/pricebands/{priceBandFid}][%d] getProductsProductFidPricebandsPriceBandFidOK %s", 200, payload)
}

func (o *GetProductsProductFidPricebandsPriceBandFidOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/pricebands/{priceBandFid}][%d] getProductsProductFidPricebandsPriceBandFidOK %s", 200, payload)
}

func (o *GetProductsProductFidPricebandsPriceBandFidOK) GetPayload() *GetProductsProductFidPricebandsPriceBandFidOKBody {
	return o.Payload
}

func (o *GetProductsProductFidPricebandsPriceBandFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetProductsProductFidPricebandsPriceBandFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductsProductFidPricebandsPriceBandFidDefault creates a GetProductsProductFidPricebandsPriceBandFidDefault with default headers values
func NewGetProductsProductFidPricebandsPriceBandFidDefault(code int) *GetProductsProductFidPricebandsPriceBandFidDefault {
	return &GetProductsProductFidPricebandsPriceBandFidDefault{
		_statusCode: code,
	}
}

/*
GetProductsProductFidPricebandsPriceBandFidDefault describes a response with status code -1, with default header values.

Error
*/
type GetProductsProductFidPricebandsPriceBandFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get products product fid pricebands price band fid default response has a 2xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get products product fid pricebands price band fid default response has a 3xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get products product fid pricebands price band fid default response has a 4xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get products product fid pricebands price band fid default response has a 5xx status code
func (o *GetProductsProductFidPricebandsPriceBandFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get products product fid pricebands price band fid default response a status code equal to that given
func (o *GetProductsProductFidPricebandsPriceBandFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get products product fid pricebands price band fid default response
func (o *GetProductsProductFidPricebandsPriceBandFidDefault) Code() int {
	return o._statusCode
}

func (o *GetProductsProductFidPricebandsPriceBandFidDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/pricebands/{priceBandFid}][%d] GetProductsProductFidPricebandsPriceBandFid default %s", o._statusCode, payload)
}

func (o *GetProductsProductFidPricebandsPriceBandFidDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{productFid}/pricebands/{priceBandFid}][%d] GetProductsProductFidPricebandsPriceBandFid default %s", o._statusCode, payload)
}

func (o *GetProductsProductFidPricebandsPriceBandFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetProductsProductFidPricebandsPriceBandFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetProductsProductFidPricebandsPriceBandFidOKBody get products product fid pricebands price band fid o k body
swagger:model GetProductsProductFidPricebandsPriceBandFidOKBody
*/
type GetProductsProductFidPricebandsPriceBandFidOKBody struct {
	models.Envelope

	// data
	Data *models.ProductPriceBand `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetProductsProductFidPricebandsPriceBandFidOKBody) UnmarshalJSON(raw []byte) error {
	// GetProductsProductFidPricebandsPriceBandFidOKBodyAO0
	var getProductsProductFidPricebandsPriceBandFidOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getProductsProductFidPricebandsPriceBandFidOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getProductsProductFidPricebandsPriceBandFidOKBodyAO0

	// GetProductsProductFidPricebandsPriceBandFidOKBodyAO1
	var dataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1 struct {
		Data *models.ProductPriceBand `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetProductsProductFidPricebandsPriceBandFidOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getProductsProductFidPricebandsPriceBandFidOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getProductsProductFidPricebandsPriceBandFidOKBodyAO0)
	var dataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1 struct {
		Data *models.ProductPriceBand `json:"data,omitempty"`
	}

	dataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1.Data = o.Data

	jsonDataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1, errGetProductsProductFidPricebandsPriceBandFidOKBodyAO1 := swag.WriteJSON(dataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1)
	if errGetProductsProductFidPricebandsPriceBandFidOKBodyAO1 != nil {
		return nil, errGetProductsProductFidPricebandsPriceBandFidOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetProductsProductFidPricebandsPriceBandFidOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get products product fid pricebands price band fid o k body
func (o *GetProductsProductFidPricebandsPriceBandFidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetProductsProductFidPricebandsPriceBandFidOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getProductsProductFidPricebandsPriceBandFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getProductsProductFidPricebandsPriceBandFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get products product fid pricebands price band fid o k body based on the context it is used
func (o *GetProductsProductFidPricebandsPriceBandFidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetProductsProductFidPricebandsPriceBandFidOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getProductsProductFidPricebandsPriceBandFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getProductsProductFidPricebandsPriceBandFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetProductsProductFidPricebandsPriceBandFidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProductsProductFidPricebandsPriceBandFidOKBody) UnmarshalBinary(b []byte) error {
	var res GetProductsProductFidPricebandsPriceBandFidOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
