// Code generated by go-swagger; DO NOT EDIT.

package products

import (
	"context"
	"net/http"
	"time"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostProductsGroupsParams creates a new PostProductsGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProductsGroupsParams() *PostProductsGroupsParams {
	return NewPostProductsGroupsParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostProductsGroupsParamsWithTimeout creates a new PostProductsGroupsParams object
// with the ability to set a timeout on a request.
func NewPostProductsGroupsParamsWithTimeout(timeout time.Duration) *PostProductsGroupsParams {
	return &PostProductsGroupsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostProductsGroupsParamsWithContext creates a new PostProductsGroupsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostProductsGroupsParams].
func NewPostProductsGroupsParamsWithContext(ctx context.Context) *PostProductsGroupsParams {
	return &PostProductsGroupsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostProductsGroupsParamsWithHTTPClient creates a new PostProductsGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProductsGroupsParamsWithHTTPClient(client *http.Client) *PostProductsGroupsParams {
	return &PostProductsGroupsParams{
		HTTPClient: client,
	}
}

/*
PostProductsGroupsParams contains all the parameters to send to the API endpoint

	for the post products groups operation.

	Typically these are written to a http.Request.
*/
type PostProductsGroupsParams struct {

	// Payload.
	Payload *models.CreateProductGroupPayload

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post products groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProductsGroupsParams) WithDefaults() *PostProductsGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post products groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProductsGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post products groups params.
func (o *PostProductsGroupsParams) WithTimeout(timeout time.Duration) *PostProductsGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post products groups params.
func (o *PostProductsGroupsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post products groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostProductsGroupsParams].
func (o *PostProductsGroupsParams) WithContext(ctx context.Context) *PostProductsGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post products groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostProductsGroupsParams].
func (o *PostProductsGroupsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post products groups params.
func (o *PostProductsGroupsParams) WithHTTPClient(client *http.Client) *PostProductsGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post products groups params.
func (o *PostProductsGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the post products groups params.
func (o *PostProductsGroupsParams) WithPayload(payload *models.CreateProductGroupPayload) *PostProductsGroupsParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post products groups params.
func (o *PostProductsGroupsParams) SetPayload(payload *models.CreateProductGroupPayload) {
	o.Payload = payload
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostProductsGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
