// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// NewPostProductsProductFidPricebandsParams creates a new PostProductsProductFidPricebandsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProductsProductFidPricebandsParams() *PostProductsProductFidPricebandsParams {
	return &PostProductsProductFidPricebandsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProductsProductFidPricebandsParamsWithTimeout creates a new PostProductsProductFidPricebandsParams object
// with the ability to set a timeout on a request.
func NewPostProductsProductFidPricebandsParamsWithTimeout(timeout time.Duration) *PostProductsProductFidPricebandsParams {
	return &PostProductsProductFidPricebandsParams{
		timeout: timeout,
	}
}

// NewPostProductsProductFidPricebandsParamsWithContext creates a new PostProductsProductFidPricebandsParams object
// with the ability to set a context for a request.
func NewPostProductsProductFidPricebandsParamsWithContext(ctx context.Context) *PostProductsProductFidPricebandsParams {
	return &PostProductsProductFidPricebandsParams{
		Context: ctx,
	}
}

// NewPostProductsProductFidPricebandsParamsWithHTTPClient creates a new PostProductsProductFidPricebandsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProductsProductFidPricebandsParamsWithHTTPClient(client *http.Client) *PostProductsProductFidPricebandsParams {
	return &PostProductsProductFidPricebandsParams{
		HTTPClient: client,
	}
}

/*
PostProductsProductFidPricebandsParams contains all the parameters to send to the API endpoint

	for the post products product fid pricebands operation.

	Typically these are written to a http.Request.
*/
type PostProductsProductFidPricebandsParams struct {

	// Payload.
	Payload *models.CreateProductPriceBandPayload

	// ProductFid.
	ProductFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post products product fid pricebands params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProductsProductFidPricebandsParams) WithDefaults() *PostProductsProductFidPricebandsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post products product fid pricebands params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProductsProductFidPricebandsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) WithTimeout(timeout time.Duration) *PostProductsProductFidPricebandsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) WithContext(ctx context.Context) *PostProductsProductFidPricebandsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) WithHTTPClient(client *http.Client) *PostProductsProductFidPricebandsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) WithPayload(payload *models.CreateProductPriceBandPayload) *PostProductsProductFidPricebandsParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) SetPayload(payload *models.CreateProductPriceBandPayload) {
	o.Payload = payload
}

// WithProductFid adds the productFid to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) WithProductFid(productFid string) *PostProductsProductFidPricebandsParams {
	o.SetProductFid(productFid)
	return o
}

// SetProductFid adds the productFid to the post products product fid pricebands params
func (o *PostProductsProductFidPricebandsParams) SetProductFid(productFid string) {
	o.ProductFid = productFid
}

// WriteToRequest writes these params to a swagger request
func (o *PostProductsProductFidPricebandsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	// path param productFid
	if err := r.SetPathParam("productFid", o.ProductFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
