// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new products API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new products API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new products API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for products API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteProductsGroupsProductGroupFidProductsProductFid(params *DeleteProductsGroupsProductGroupFidProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProductsGroupsProductGroupFidProductsProductFidOK, error)

	GetProducts(params *GetProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsOK, error)

	GetProductsGroups(params *GetProductsGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsGroupsOK, error)

	GetProductsGroupsProductGroupFid(params *GetProductsGroupsProductGroupFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsGroupsProductGroupFidOK, error)

	GetProductsGroupsProductGroupFidProducts(params *GetProductsGroupsProductGroupFidProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsGroupsProductGroupFidProductsOK, error)

	GetProductsOffers(params *GetProductsOffersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsOffersOK, error)

	GetProductsOffersOfferFid(params *GetProductsOffersOfferFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsOffersOfferFidOK, error)

	GetProductsProductFid(params *GetProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidOK, error)

	GetProductsProductFidPricebands(params *GetProductsProductFidPricebandsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricebandsOK, error)

	GetProductsProductFidPricebandsPriceBandFid(params *GetProductsProductFidPricebandsPriceBandFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricebandsPriceBandFidOK, error)

	GetProductsProductFidPrices(params *GetProductsProductFidPricesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricesOK, error)

	GetProductsProductFidPricesPriceFid(params *GetProductsProductFidPricesPriceFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricesPriceFidOK, error)

	GetProductsProductFidSkus(params *GetProductsProductFidSkusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidSkusOK, error)

	GetProductsProductFidSkusSkuFid(params *GetProductsProductFidSkusSkuFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidSkusSkuFidOK, error)

	PostProducts(params *PostProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsOK, error)

	PostProductsGroups(params *PostProductsGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsGroupsOK, error)

	PostProductsGroupsProductGroupFidProductsProductFid(params *PostProductsGroupsProductGroupFidProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsGroupsProductGroupFidProductsProductFidOK, error)

	PostProductsOffers(params *PostProductsOffersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsOffersOK, error)

	PostProductsProductFidAvailabilityCheck(params *PostProductsProductFidAvailabilityCheckParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidAvailabilityCheckOK, error)

	PostProductsProductFidAvailabilityReserve(params *PostProductsProductFidAvailabilityReserveParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidAvailabilityReserveOK, error)

	PostProductsProductFidPricebands(params *PostProductsProductFidPricebandsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidPricebandsOK, error)

	PostProductsProductFidPrices(params *PostProductsProductFidPricesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidPricesOK, error)

	PostProductsProductFidSkus(params *PostProductsProductFidSkusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidSkusOK, error)

	PutProductsGroupsProductGroupFid(params *PutProductsGroupsProductGroupFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsGroupsProductGroupFidOK, error)

	PutProductsOffersOfferFid(params *PutProductsOffersOfferFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsOffersOfferFidOK, error)

	PutProductsProductFid(params *PutProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidOK, error)

	PutProductsProductFidPricebandsPriceBandFid(params *PutProductsProductFidPricebandsPriceBandFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidPricebandsPriceBandFidOK, error)

	PutProductsProductFidPricesPriceFid(params *PutProductsProductFidPricesPriceFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidPricesPriceFidOK, error)

	PutProductsProductFidSkusSkuFid(params *PutProductsProductFidSkusSkuFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidSkusSkuFidOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteProductsGroupsProductGroupFidProductsProductFid removes a product from the group
*/
func (a *Client) DeleteProductsGroupsProductGroupFidProductsProductFid(params *DeleteProductsGroupsProductGroupFidProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProductsGroupsProductGroupFidProductsProductFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProductsGroupsProductGroupFidProductsProductFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteProductsGroupsProductGroupFidProductsProductFid",
		Method:             "DELETE",
		PathPattern:        "/products/groups/{productGroupFid}/products/{productFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteProductsGroupsProductGroupFidProductsProductFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProductsGroupsProductGroupFidProductsProductFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*DeleteProductsGroupsProductGroupFidProductsProductFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProducts lists all products
*/
func (a *Client) GetProducts(params *GetProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProducts",
		Method:             "GET",
		PathPattern:        "/products",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsGroups gets a list of all product groups
*/
func (a *Client) GetProductsGroups(params *GetProductsGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsGroupsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsGroupsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsGroups",
		Method:             "GET",
		PathPattern:        "/products/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsGroupsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsGroupsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsGroupsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsGroupsProductGroupFid retrieves product group details
*/
func (a *Client) GetProductsGroupsProductGroupFid(params *GetProductsGroupsProductGroupFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsGroupsProductGroupFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsGroupsProductGroupFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsGroupsProductGroupFid",
		Method:             "GET",
		PathPattern:        "/products/groups/{productGroupFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsGroupsProductGroupFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsGroupsProductGroupFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsGroupsProductGroupFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsGroupsProductGroupFidProducts gets a list of products belonging to the group
*/
func (a *Client) GetProductsGroupsProductGroupFidProducts(params *GetProductsGroupsProductGroupFidProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsGroupsProductGroupFidProductsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsGroupsProductGroupFidProductsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsGroupsProductGroupFidProducts",
		Method:             "GET",
		PathPattern:        "/products/groups/{productGroupFid}/products",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsGroupsProductGroupFidProductsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsGroupsProductGroupFidProductsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsGroupsProductGroupFidProductsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsOffers retrieves all offers
*/
func (a *Client) GetProductsOffers(params *GetProductsOffersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsOffersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsOffersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsOffers",
		Method:             "GET",
		PathPattern:        "/products/offers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsOffersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsOffersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsOffersDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsOffersOfferFid retrieves offer details
*/
func (a *Client) GetProductsOffersOfferFid(params *GetProductsOffersOfferFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsOffersOfferFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsOffersOfferFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsOffersOfferFid",
		Method:             "GET",
		PathPattern:        "/products/offers/{offerFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsOffersOfferFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsOffersOfferFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsOffersOfferFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsProductFid retrieves product details
*/
func (a *Client) GetProductsProductFid(params *GetProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsProductFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsProductFid",
		Method:             "GET",
		PathPattern:        "/products/{productFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsProductFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsProductFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsProductFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsProductFidPricebands retrieves product price bands
*/
func (a *Client) GetProductsProductFidPricebands(params *GetProductsProductFidPricebandsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricebandsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsProductFidPricebandsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsProductFidPricebands",
		Method:             "GET",
		PathPattern:        "/products/{productFid}/pricebands",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsProductFidPricebandsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsProductFidPricebandsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsProductFidPricebandsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsProductFidPricebandsPriceBandFid retrieves product price band details
*/
func (a *Client) GetProductsProductFidPricebandsPriceBandFid(params *GetProductsProductFidPricebandsPriceBandFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricebandsPriceBandFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsProductFidPricebandsPriceBandFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsProductFidPricebandsPriceBandFid",
		Method:             "GET",
		PathPattern:        "/products/{productFid}/pricebands/{priceBandFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsProductFidPricebandsPriceBandFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsProductFidPricebandsPriceBandFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsProductFidPricebandsPriceBandFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsProductFidPrices retrieves product prices
*/
func (a *Client) GetProductsProductFidPrices(params *GetProductsProductFidPricesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsProductFidPricesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsProductFidPrices",
		Method:             "GET",
		PathPattern:        "/products/{productFid}/prices",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsProductFidPricesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsProductFidPricesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsProductFidPricesDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsProductFidPricesPriceFid retrieves product price details
*/
func (a *Client) GetProductsProductFidPricesPriceFid(params *GetProductsProductFidPricesPriceFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidPricesPriceFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsProductFidPricesPriceFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsProductFidPricesPriceFid",
		Method:             "GET",
		PathPattern:        "/products/{productFid}/prices/{priceFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsProductFidPricesPriceFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsProductFidPricesPriceFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsProductFidPricesPriceFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsProductFidSkus retrieves product s k us
*/
func (a *Client) GetProductsProductFidSkus(params *GetProductsProductFidSkusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidSkusOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsProductFidSkusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsProductFidSkus",
		Method:             "GET",
		PathPattern:        "/products/{productFid}/skus",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsProductFidSkusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsProductFidSkusOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsProductFidSkusDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetProductsProductFidSkusSkuFid retrieves product s k u details
*/
func (a *Client) GetProductsProductFidSkusSkuFid(params *GetProductsProductFidSkusSkuFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProductsProductFidSkusSkuFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProductsProductFidSkusSkuFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProductsProductFidSkusSkuFid",
		Method:             "GET",
		PathPattern:        "/products/{productFid}/skus/{skuFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProductsProductFidSkusSkuFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProductsProductFidSkusSkuFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetProductsProductFidSkusSkuFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProducts creates a new product
*/
func (a *Client) PostProducts(params *PostProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProducts",
		Method:             "POST",
		PathPattern:        "/products",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsGroups creates a new product group
*/
func (a *Client) PostProductsGroups(params *PostProductsGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsGroupsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsGroupsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsGroups",
		Method:             "POST",
		PathPattern:        "/products/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsGroupsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsGroupsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsGroupsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsGroupsProductGroupFidProductsProductFid adds a product to the group
*/
func (a *Client) PostProductsGroupsProductGroupFidProductsProductFid(params *PostProductsGroupsProductGroupFidProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsGroupsProductGroupFidProductsProductFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsGroupsProductGroupFidProductsProductFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsGroupsProductGroupFidProductsProductFid",
		Method:             "POST",
		PathPattern:        "/products/groups/{productGroupFid}/products/{productFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsGroupsProductGroupFidProductsProductFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsGroupsProductGroupFidProductsProductFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsGroupsProductGroupFidProductsProductFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsOffers creates a new offer
*/
func (a *Client) PostProductsOffers(params *PostProductsOffersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsOffersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsOffersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsOffers",
		Method:             "POST",
		PathPattern:        "/products/offers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsOffersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsOffersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsOffersDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsProductFidAvailabilityCheck checks product availability
*/
func (a *Client) PostProductsProductFidAvailabilityCheck(params *PostProductsProductFidAvailabilityCheckParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidAvailabilityCheckOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsProductFidAvailabilityCheckParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsProductFidAvailabilityCheck",
		Method:             "POST",
		PathPattern:        "/products/{productFid}/availability/check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsProductFidAvailabilityCheckReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsProductFidAvailabilityCheckOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsProductFidAvailabilityCheckDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsProductFidAvailabilityReserve reserves product
*/
func (a *Client) PostProductsProductFidAvailabilityReserve(params *PostProductsProductFidAvailabilityReserveParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidAvailabilityReserveOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsProductFidAvailabilityReserveParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsProductFidAvailabilityReserve",
		Method:             "POST",
		PathPattern:        "/products/{productFid}/availability/reserve",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsProductFidAvailabilityReserveReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsProductFidAvailabilityReserveOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsProductFidAvailabilityReserveDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsProductFidPricebands creates a new product price band
*/
func (a *Client) PostProductsProductFidPricebands(params *PostProductsProductFidPricebandsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidPricebandsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsProductFidPricebandsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsProductFidPricebands",
		Method:             "POST",
		PathPattern:        "/products/{productFid}/pricebands",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsProductFidPricebandsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsProductFidPricebandsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsProductFidPricebandsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsProductFidPrices creates a new product price
*/
func (a *Client) PostProductsProductFidPrices(params *PostProductsProductFidPricesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidPricesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsProductFidPricesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsProductFidPrices",
		Method:             "POST",
		PathPattern:        "/products/{productFid}/prices",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsProductFidPricesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsProductFidPricesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsProductFidPricesDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostProductsProductFidSkus creates a new product s k u
*/
func (a *Client) PostProductsProductFidSkus(params *PostProductsProductFidSkusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProductsProductFidSkusOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProductsProductFidSkusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProductsProductFidSkus",
		Method:             "POST",
		PathPattern:        "/products/{productFid}/skus",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostProductsProductFidSkusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProductsProductFidSkusOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostProductsProductFidSkusDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PutProductsGroupsProductGroupFid updates product group details
*/
func (a *Client) PutProductsGroupsProductGroupFid(params *PutProductsGroupsProductGroupFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsGroupsProductGroupFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProductsGroupsProductGroupFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProductsGroupsProductGroupFid",
		Method:             "PUT",
		PathPattern:        "/products/groups/{productGroupFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutProductsGroupsProductGroupFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProductsGroupsProductGroupFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PutProductsGroupsProductGroupFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PutProductsOffersOfferFid updates offer details
*/
func (a *Client) PutProductsOffersOfferFid(params *PutProductsOffersOfferFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsOffersOfferFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProductsOffersOfferFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProductsOffersOfferFid",
		Method:             "PUT",
		PathPattern:        "/products/offers/{offerFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutProductsOffersOfferFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProductsOffersOfferFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PutProductsOffersOfferFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PutProductsProductFid updates product details
*/
func (a *Client) PutProductsProductFid(params *PutProductsProductFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProductsProductFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProductsProductFid",
		Method:             "PUT",
		PathPattern:        "/products/{productFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutProductsProductFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProductsProductFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PutProductsProductFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PutProductsProductFidPricebandsPriceBandFid updates product price band details
*/
func (a *Client) PutProductsProductFidPricebandsPriceBandFid(params *PutProductsProductFidPricebandsPriceBandFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidPricebandsPriceBandFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProductsProductFidPricebandsPriceBandFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProductsProductFidPricebandsPriceBandFid",
		Method:             "PUT",
		PathPattern:        "/products/{productFid}/pricebands/{priceBandFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutProductsProductFidPricebandsPriceBandFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProductsProductFidPricebandsPriceBandFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PutProductsProductFidPricebandsPriceBandFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PutProductsProductFidPricesPriceFid updates product price details
*/
func (a *Client) PutProductsProductFidPricesPriceFid(params *PutProductsProductFidPricesPriceFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidPricesPriceFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProductsProductFidPricesPriceFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProductsProductFidPricesPriceFid",
		Method:             "PUT",
		PathPattern:        "/products/{productFid}/prices/{priceFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutProductsProductFidPricesPriceFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProductsProductFidPricesPriceFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PutProductsProductFidPricesPriceFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PutProductsProductFidSkusSkuFid updates product s k u details
*/
func (a *Client) PutProductsProductFidSkusSkuFid(params *PutProductsProductFidSkusSkuFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProductsProductFidSkusSkuFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProductsProductFidSkusSkuFidParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProductsProductFidSkusSkuFid",
		Method:             "PUT",
		PathPattern:        "/products/{productFid}/skus/{skuFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutProductsProductFidSkusSkuFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProductsProductFidSkusSkuFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PutProductsProductFidSkusSkuFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
