// Code generated by go-swagger; DO NOT EDIT.

package products

import (
	"context"
	"net/http"
	"time"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutProductsOffersOfferFidParams creates a new PutProductsOffersOfferFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProductsOffersOfferFidParams() *PutProductsOffersOfferFidParams {
	return NewPutProductsOffersOfferFidParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutProductsOffersOfferFidParamsWithTimeout creates a new PutProductsOffersOfferFidParams object
// with the ability to set a timeout on a request.
func NewPutProductsOffersOfferFidParamsWithTimeout(timeout time.Duration) *PutProductsOffersOfferFidParams {
	return &PutProductsOffersOfferFidParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutProductsOffersOfferFidParamsWithContext creates a new PutProductsOffersOfferFidParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProductsOffersOfferFidParams].
func NewPutProductsOffersOfferFidParamsWithContext(ctx context.Context) *PutProductsOffersOfferFidParams {
	return &PutProductsOffersOfferFidParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutProductsOffersOfferFidParamsWithHTTPClient creates a new PutProductsOffersOfferFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProductsOffersOfferFidParamsWithHTTPClient(client *http.Client) *PutProductsOffersOfferFidParams {
	return &PutProductsOffersOfferFidParams{
		HTTPClient: client,
	}
}

/*
PutProductsOffersOfferFidParams contains all the parameters to send to the API endpoint

	for the put products offers offer fid operation.

	Typically these are written to a http.Request.
*/
type PutProductsOffersOfferFidParams struct {

	/* OfferFid.

	   Offer FID or Coupon Code
	*/
	OfferFid string

	// Payload.
	Payload *models.UpdateProductOfferPayload

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put products offers offer fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsOffersOfferFidParams) WithDefaults() *PutProductsOffersOfferFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put products offers offer fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsOffersOfferFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) WithTimeout(timeout time.Duration) *PutProductsOffersOfferFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put products offers offer fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProductsOffersOfferFidParams].
func (o *PutProductsOffersOfferFidParams) WithContext(ctx context.Context) *PutProductsOffersOfferFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put products offers offer fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProductsOffersOfferFidParams].
func (o *PutProductsOffersOfferFidParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) WithHTTPClient(client *http.Client) *PutProductsOffersOfferFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOfferFid adds the offerFid to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) WithOfferFid(offerFid string) *PutProductsOffersOfferFidParams {
	o.SetOfferFid(offerFid)
	return o
}

// SetOfferFid adds the offerFid to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) SetOfferFid(offerFid string) {
	o.OfferFid = offerFid
}

// WithPayload adds the payload to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) WithPayload(payload *models.UpdateProductOfferPayload) *PutProductsOffersOfferFidParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put products offers offer fid params.
func (o *PutProductsOffersOfferFidParams) SetPayload(payload *models.UpdateProductOfferPayload) {
	o.Payload = payload
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutProductsOffersOfferFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param offerFid
	if err := r.SetPathParam("offerFid", o.OfferFid); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
