// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// NewPutProductsProductFidPricebandsPriceBandFidParams creates a new PutProductsProductFidPricebandsPriceBandFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProductsProductFidPricebandsPriceBandFidParams() *PutProductsProductFidPricebandsPriceBandFidParams {
	return &PutProductsProductFidPricebandsPriceBandFidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProductsProductFidPricebandsPriceBandFidParamsWithTimeout creates a new PutProductsProductFidPricebandsPriceBandFidParams object
// with the ability to set a timeout on a request.
func NewPutProductsProductFidPricebandsPriceBandFidParamsWithTimeout(timeout time.Duration) *PutProductsProductFidPricebandsPriceBandFidParams {
	return &PutProductsProductFidPricebandsPriceBandFidParams{
		timeout: timeout,
	}
}

// NewPutProductsProductFidPricebandsPriceBandFidParamsWithContext creates a new PutProductsProductFidPricebandsPriceBandFidParams object
// with the ability to set a context for a request.
func NewPutProductsProductFidPricebandsPriceBandFidParamsWithContext(ctx context.Context) *PutProductsProductFidPricebandsPriceBandFidParams {
	return &PutProductsProductFidPricebandsPriceBandFidParams{
		Context: ctx,
	}
}

// NewPutProductsProductFidPricebandsPriceBandFidParamsWithHTTPClient creates a new PutProductsProductFidPricebandsPriceBandFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProductsProductFidPricebandsPriceBandFidParamsWithHTTPClient(client *http.Client) *PutProductsProductFidPricebandsPriceBandFidParams {
	return &PutProductsProductFidPricebandsPriceBandFidParams{
		HTTPClient: client,
	}
}

/*
PutProductsProductFidPricebandsPriceBandFidParams contains all the parameters to send to the API endpoint

	for the put products product fid pricebands price band fid operation.

	Typically these are written to a http.Request.
*/
type PutProductsProductFidPricebandsPriceBandFidParams struct {

	// Payload.
	Payload *models.UpdateProductPriceBandPayload

	// PriceBandFid.
	PriceBandFid string

	// ProductFid.
	ProductFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put products product fid pricebands price band fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WithDefaults() *PutProductsProductFidPricebandsPriceBandFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put products product fid pricebands price band fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsProductFidPricebandsPriceBandFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WithTimeout(timeout time.Duration) *PutProductsProductFidPricebandsPriceBandFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WithContext(ctx context.Context) *PutProductsProductFidPricebandsPriceBandFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WithHTTPClient(client *http.Client) *PutProductsProductFidPricebandsPriceBandFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WithPayload(payload *models.UpdateProductPriceBandPayload) *PutProductsProductFidPricebandsPriceBandFidParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) SetPayload(payload *models.UpdateProductPriceBandPayload) {
	o.Payload = payload
}

// WithPriceBandFid adds the priceBandFid to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WithPriceBandFid(priceBandFid string) *PutProductsProductFidPricebandsPriceBandFidParams {
	o.SetPriceBandFid(priceBandFid)
	return o
}

// SetPriceBandFid adds the priceBandFid to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) SetPriceBandFid(priceBandFid string) {
	o.PriceBandFid = priceBandFid
}

// WithProductFid adds the productFid to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WithProductFid(productFid string) *PutProductsProductFidPricebandsPriceBandFidParams {
	o.SetProductFid(productFid)
	return o
}

// SetProductFid adds the productFid to the put products product fid pricebands price band fid params
func (o *PutProductsProductFidPricebandsPriceBandFidParams) SetProductFid(productFid string) {
	o.ProductFid = productFid
}

// WriteToRequest writes these params to a swagger request
func (o *PutProductsProductFidPricebandsPriceBandFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	// path param priceBandFid
	if err := r.SetPathParam("priceBandFid", o.PriceBandFid); err != nil {
		return err
	}

	// path param productFid
	if err := r.SetPathParam("productFid", o.ProductFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
