// Code generated by go-swagger; DO NOT EDIT.

package products

import (
	"context"
	"net/http"
	"time"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutProductsGroupsProductGroupFidParams creates a new PutProductsGroupsProductGroupFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProductsGroupsProductGroupFidParams() *PutProductsGroupsProductGroupFidParams {
	return NewPutProductsGroupsProductGroupFidParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutProductsGroupsProductGroupFidParamsWithTimeout creates a new PutProductsGroupsProductGroupFidParams object
// with the ability to set a timeout on a request.
func NewPutProductsGroupsProductGroupFidParamsWithTimeout(timeout time.Duration) *PutProductsGroupsProductGroupFidParams {
	return &PutProductsGroupsProductGroupFidParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutProductsGroupsProductGroupFidParamsWithContext creates a new PutProductsGroupsProductGroupFidParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProductsGroupsProductGroupFidParams].
func NewPutProductsGroupsProductGroupFidParamsWithContext(ctx context.Context) *PutProductsGroupsProductGroupFidParams {
	return &PutProductsGroupsProductGroupFidParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutProductsGroupsProductGroupFidParamsWithHTTPClient creates a new PutProductsGroupsProductGroupFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProductsGroupsProductGroupFidParamsWithHTTPClient(client *http.Client) *PutProductsGroupsProductGroupFidParams {
	return &PutProductsGroupsProductGroupFidParams{
		HTTPClient: client,
	}
}

/*
PutProductsGroupsProductGroupFidParams contains all the parameters to send to the API endpoint

	for the put products groups product group fid operation.

	Typically these are written to a http.Request.
*/
type PutProductsGroupsProductGroupFidParams struct {

	// Payload.
	Payload *models.UpdateProductGroupPayload

	// ProductGroupFid.
	ProductGroupFid string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put products groups product group fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsGroupsProductGroupFidParams) WithDefaults() *PutProductsGroupsProductGroupFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put products groups product group fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsGroupsProductGroupFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) WithTimeout(timeout time.Duration) *PutProductsGroupsProductGroupFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put products groups product group fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProductsGroupsProductGroupFidParams].
func (o *PutProductsGroupsProductGroupFidParams) WithContext(ctx context.Context) *PutProductsGroupsProductGroupFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put products groups product group fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProductsGroupsProductGroupFidParams].
func (o *PutProductsGroupsProductGroupFidParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) WithHTTPClient(client *http.Client) *PutProductsGroupsProductGroupFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) WithPayload(payload *models.UpdateProductGroupPayload) *PutProductsGroupsProductGroupFidParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) SetPayload(payload *models.UpdateProductGroupPayload) {
	o.Payload = payload
}

// WithProductGroupFid adds the productGroupFid to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) WithProductGroupFid(productGroupFid string) *PutProductsGroupsProductGroupFidParams {
	o.SetProductGroupFid(productGroupFid)
	return o
}

// SetProductGroupFid adds the productGroupFid to the put products groups product group fid params.
func (o *PutProductsGroupsProductGroupFidParams) SetProductGroupFid(productGroupFid string) {
	o.ProductGroupFid = productGroupFid
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutProductsGroupsProductGroupFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	// path param productGroupFid
	if err := r.SetPathParam("productGroupFid", o.ProductGroupFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
