// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// NewPutProductsProductFidSkusSkuFidParams creates a new PutProductsProductFidSkusSkuFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProductsProductFidSkusSkuFidParams() *PutProductsProductFidSkusSkuFidParams {
	return &PutProductsProductFidSkusSkuFidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProductsProductFidSkusSkuFidParamsWithTimeout creates a new PutProductsProductFidSkusSkuFidParams object
// with the ability to set a timeout on a request.
func NewPutProductsProductFidSkusSkuFidParamsWithTimeout(timeout time.Duration) *PutProductsProductFidSkusSkuFidParams {
	return &PutProductsProductFidSkusSkuFidParams{
		timeout: timeout,
	}
}

// NewPutProductsProductFidSkusSkuFidParamsWithContext creates a new PutProductsProductFidSkusSkuFidParams object
// with the ability to set a context for a request.
func NewPutProductsProductFidSkusSkuFidParamsWithContext(ctx context.Context) *PutProductsProductFidSkusSkuFidParams {
	return &PutProductsProductFidSkusSkuFidParams{
		Context: ctx,
	}
}

// NewPutProductsProductFidSkusSkuFidParamsWithHTTPClient creates a new PutProductsProductFidSkusSkuFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProductsProductFidSkusSkuFidParamsWithHTTPClient(client *http.Client) *PutProductsProductFidSkusSkuFidParams {
	return &PutProductsProductFidSkusSkuFidParams{
		HTTPClient: client,
	}
}

/*
PutProductsProductFidSkusSkuFidParams contains all the parameters to send to the API endpoint

	for the put products product fid skus sku fid operation.

	Typically these are written to a http.Request.
*/
type PutProductsProductFidSkusSkuFidParams struct {

	// Payload.
	Payload *models.UpdateProductSkuPayload

	// ProductFid.
	ProductFid string

	// SkuFid.
	SkuFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put products product fid skus sku fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsProductFidSkusSkuFidParams) WithDefaults() *PutProductsProductFidSkusSkuFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put products product fid skus sku fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsProductFidSkusSkuFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) WithTimeout(timeout time.Duration) *PutProductsProductFidSkusSkuFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) WithContext(ctx context.Context) *PutProductsProductFidSkusSkuFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) WithHTTPClient(client *http.Client) *PutProductsProductFidSkusSkuFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) WithPayload(payload *models.UpdateProductSkuPayload) *PutProductsProductFidSkusSkuFidParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) SetPayload(payload *models.UpdateProductSkuPayload) {
	o.Payload = payload
}

// WithProductFid adds the productFid to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) WithProductFid(productFid string) *PutProductsProductFidSkusSkuFidParams {
	o.SetProductFid(productFid)
	return o
}

// SetProductFid adds the productFid to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) SetProductFid(productFid string) {
	o.ProductFid = productFid
}

// WithSkuFid adds the skuFid to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) WithSkuFid(skuFid string) *PutProductsProductFidSkusSkuFidParams {
	o.SetSkuFid(skuFid)
	return o
}

// SetSkuFid adds the skuFid to the put products product fid skus sku fid params
func (o *PutProductsProductFidSkusSkuFidParams) SetSkuFid(skuFid string) {
	o.SkuFid = skuFid
}

// WriteToRequest writes these params to a swagger request
func (o *PutProductsProductFidSkusSkuFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	// path param productFid
	if err := r.SetPathParam("productFid", o.ProductFid); err != nil {
		return err
	}

	// path param skuFid
	if err := r.SetPathParam("skuFid", o.SkuFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
