// Code generated by go-swagger; DO NOT EDIT.

package reviews

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// PutReviewReviewFidReader is a Reader for the PutReviewReviewFid structure.
type PutReviewReviewFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutReviewReviewFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutReviewReviewFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutReviewReviewFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutReviewReviewFidOK creates a PutReviewReviewFidOK with default headers values
func NewPutReviewReviewFidOK() *PutReviewReviewFidOK {
	return &PutReviewReviewFidOK{}
}

/*
PutReviewReviewFidOK describes a response with status code 200, with default header values.

Review Update
*/
type PutReviewReviewFidOK struct {
	Payload *PutReviewReviewFidOKBody
}

// IsSuccess returns true when this put review review fid o k response has a 2xx status code
func (o *PutReviewReviewFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put review review fid o k response has a 3xx status code
func (o *PutReviewReviewFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put review review fid o k response has a 4xx status code
func (o *PutReviewReviewFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put review review fid o k response has a 5xx status code
func (o *PutReviewReviewFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put review review fid o k response a status code equal to that given
func (o *PutReviewReviewFidOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put review review fid o k response
func (o *PutReviewReviewFidOK) Code() int {
	return 200
}

func (o *PutReviewReviewFidOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /review/{reviewFid}][%d] putReviewReviewFidOK %s", 200, payload)
}

func (o *PutReviewReviewFidOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /review/{reviewFid}][%d] putReviewReviewFidOK %s", 200, payload)
}

func (o *PutReviewReviewFidOK) GetPayload() *PutReviewReviewFidOKBody {
	return o.Payload
}

func (o *PutReviewReviewFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PutReviewReviewFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutReviewReviewFidDefault creates a PutReviewReviewFidDefault with default headers values
func NewPutReviewReviewFidDefault(code int) *PutReviewReviewFidDefault {
	return &PutReviewReviewFidDefault{
		_statusCode: code,
	}
}

/*
PutReviewReviewFidDefault describes a response with status code -1, with default header values.

Error
*/
type PutReviewReviewFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this put review review fid default response has a 2xx status code
func (o *PutReviewReviewFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put review review fid default response has a 3xx status code
func (o *PutReviewReviewFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put review review fid default response has a 4xx status code
func (o *PutReviewReviewFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put review review fid default response has a 5xx status code
func (o *PutReviewReviewFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put review review fid default response a status code equal to that given
func (o *PutReviewReviewFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put review review fid default response
func (o *PutReviewReviewFidDefault) Code() int {
	return o._statusCode
}

func (o *PutReviewReviewFidDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /review/{reviewFid}][%d] PutReviewReviewFid default %s", o._statusCode, payload)
}

func (o *PutReviewReviewFidDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /review/{reviewFid}][%d] PutReviewReviewFid default %s", o._statusCode, payload)
}

func (o *PutReviewReviewFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PutReviewReviewFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PutReviewReviewFidOKBody put review review fid o k body
swagger:model PutReviewReviewFidOKBody
*/
type PutReviewReviewFidOKBody struct {
	models.Envelope

	// data
	Data *models.BoolMessage `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PutReviewReviewFidOKBody) UnmarshalJSON(raw []byte) error {
	// PutReviewReviewFidOKBodyAO0
	var putReviewReviewFidOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &putReviewReviewFidOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = putReviewReviewFidOKBodyAO0

	// PutReviewReviewFidOKBodyAO1
	var dataPutReviewReviewFidOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPutReviewReviewFidOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataPutReviewReviewFidOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PutReviewReviewFidOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	putReviewReviewFidOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, putReviewReviewFidOKBodyAO0)
	var dataPutReviewReviewFidOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}

	dataPutReviewReviewFidOKBodyAO1.Data = o.Data

	jsonDataPutReviewReviewFidOKBodyAO1, errPutReviewReviewFidOKBodyAO1 := swag.WriteJSON(dataPutReviewReviewFidOKBodyAO1)
	if errPutReviewReviewFidOKBodyAO1 != nil {
		return nil, errPutReviewReviewFidOKBodyAO1
	}
	_parts = append(_parts, jsonDataPutReviewReviewFidOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this put review review fid o k body
func (o *PutReviewReviewFidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutReviewReviewFidOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("putReviewReviewFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("putReviewReviewFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this put review review fid o k body based on the context it is used
func (o *PutReviewReviewFidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutReviewReviewFidOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("putReviewReviewFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("putReviewReviewFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutReviewReviewFidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutReviewReviewFidOKBody) UnmarshalBinary(b []byte) error {
	var res PutReviewReviewFidOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
