// Code generated by go-swagger; DO NOT EDIT.

package brands

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBrandsParams creates a new GetBrandsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBrandsParams() *GetBrandsParams {
	return NewGetBrandsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetBrandsParamsWithTimeout creates a new GetBrandsParams object
// with the ability to set a timeout on a request.
func NewGetBrandsParamsWithTimeout(timeout time.Duration) *GetBrandsParams {
	return &GetBrandsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetBrandsParamsWithContext creates a new GetBrandsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetBrandsParams].
func NewGetBrandsParamsWithContext(ctx context.Context) *GetBrandsParams {
	return &GetBrandsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetBrandsParamsWithHTTPClient creates a new GetBrandsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBrandsParamsWithHTTPClient(client *http.Client) *GetBrandsParams {
	return &GetBrandsParams{
		HTTPClient: client,
	}
}

/*
GetBrandsParams contains all the parameters to send to the API endpoint

	for the get brands operation.

	Typically these are written to a http.Request.
*/
type GetBrandsParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get brands params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBrandsParams) WithDefaults() *GetBrandsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get brands params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBrandsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get brands params.
func (o *GetBrandsParams) WithTimeout(timeout time.Duration) *GetBrandsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get brands params.
func (o *GetBrandsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get brands params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetBrandsParams].
func (o *GetBrandsParams) WithContext(ctx context.Context) *GetBrandsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get brands params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetBrandsParams].
func (o *GetBrandsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get brands params.
func (o *GetBrandsParams) WithHTTPClient(client *http.Client) *GetBrandsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get brands params.
func (o *GetBrandsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetBrandsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
