// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFeatureFlagsPurchasePurchaseFidParams creates a new GetFeatureFlagsPurchasePurchaseFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFeatureFlagsPurchasePurchaseFidParams() *GetFeatureFlagsPurchasePurchaseFidParams {
	return &GetFeatureFlagsPurchasePurchaseFidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFeatureFlagsPurchasePurchaseFidParamsWithTimeout creates a new GetFeatureFlagsPurchasePurchaseFidParams object
// with the ability to set a timeout on a request.
func NewGetFeatureFlagsPurchasePurchaseFidParamsWithTimeout(timeout time.Duration) *GetFeatureFlagsPurchasePurchaseFidParams {
	return &GetFeatureFlagsPurchasePurchaseFidParams{
		timeout: timeout,
	}
}

// NewGetFeatureFlagsPurchasePurchaseFidParamsWithContext creates a new GetFeatureFlagsPurchasePurchaseFidParams object
// with the ability to set a context for a request.
func NewGetFeatureFlagsPurchasePurchaseFidParamsWithContext(ctx context.Context) *GetFeatureFlagsPurchasePurchaseFidParams {
	return &GetFeatureFlagsPurchasePurchaseFidParams{
		Context: ctx,
	}
}

// NewGetFeatureFlagsPurchasePurchaseFidParamsWithHTTPClient creates a new GetFeatureFlagsPurchasePurchaseFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFeatureFlagsPurchasePurchaseFidParamsWithHTTPClient(client *http.Client) *GetFeatureFlagsPurchasePurchaseFidParams {
	return &GetFeatureFlagsPurchasePurchaseFidParams{
		HTTPClient: client,
	}
}

/*
GetFeatureFlagsPurchasePurchaseFidParams contains all the parameters to send to the API endpoint

	for the get feature flags purchase purchase fid operation.

	Typically these are written to a http.Request.
*/
type GetFeatureFlagsPurchasePurchaseFidParams struct {

	/* PurchaseFid.

	   Purchase FID to use
	*/
	PurchaseFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get feature flags purchase purchase fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFeatureFlagsPurchasePurchaseFidParams) WithDefaults() *GetFeatureFlagsPurchasePurchaseFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get feature flags purchase purchase fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFeatureFlagsPurchasePurchaseFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) WithTimeout(timeout time.Duration) *GetFeatureFlagsPurchasePurchaseFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) WithContext(ctx context.Context) *GetFeatureFlagsPurchasePurchaseFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) WithHTTPClient(client *http.Client) *GetFeatureFlagsPurchasePurchaseFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPurchaseFid adds the purchaseFid to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) WithPurchaseFid(purchaseFid string) *GetFeatureFlagsPurchasePurchaseFidParams {
	o.SetPurchaseFid(purchaseFid)
	return o
}

// SetPurchaseFid adds the purchaseFid to the get feature flags purchase purchase fid params
func (o *GetFeatureFlagsPurchasePurchaseFidParams) SetPurchaseFid(purchaseFid string) {
	o.PurchaseFid = purchaseFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeatureFlagsPurchasePurchaseFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param purchaseFid
	if err := r.SetPathParam("purchaseFid", o.PurchaseFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
