// Code generated by go-swagger; DO NOT EDIT.

package account

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new account API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new account API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new account API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for account API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// PostAccountVerification main entry for verification.
	PostAccountVerification(params *PostAccountVerificationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAccountVerificationOK, error)

	// PostAccountVerificationContext main entry for verification.
	PostAccountVerificationContext(ctx context.Context, params *PostAccountVerificationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAccountVerificationOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
PostAccountVerificationmains entry for verification.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostAccountVerificationContext] instead.
*/
func (a *Client) PostAccountVerification(params *PostAccountVerificationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAccountVerificationOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostAccountVerificationContext(ctx, params, authInfo, opts...)
}

/*
PostAccountVerificationContextmains entry for verification.

Do not use the deprecated [PostAccountVerificationParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostAccountVerificationContext(ctx context.Context, params *PostAccountVerificationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAccountVerificationOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAccountVerificationParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostAccountVerification",
		Method:             "POST",
		PathPattern:        "/account/verification",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostAccountVerificationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAccountVerificationOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostAccountVerificationDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [AccountParams].
	ctx context.Context
}
