// Code generated by go-swagger; DO NOT EDIT.

package attachment

import (
	"context"
	"net/http"
	"time"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAttachmentEntityFidParams creates a new PostAttachmentEntityFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAttachmentEntityFidParams() *PostAttachmentEntityFidParams {
	return NewPostAttachmentEntityFidParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAttachmentEntityFidParamsWithTimeout creates a new PostAttachmentEntityFidParams object
// with the ability to set a timeout on a request.
func NewPostAttachmentEntityFidParamsWithTimeout(timeout time.Duration) *PostAttachmentEntityFidParams {
	return &PostAttachmentEntityFidParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAttachmentEntityFidParamsWithContext creates a new PostAttachmentEntityFidParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAttachmentEntityFidParams].
func NewPostAttachmentEntityFidParamsWithContext(ctx context.Context) *PostAttachmentEntityFidParams {
	return &PostAttachmentEntityFidParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAttachmentEntityFidParamsWithHTTPClient creates a new PostAttachmentEntityFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAttachmentEntityFidParamsWithHTTPClient(client *http.Client) *PostAttachmentEntityFidParams {
	return &PostAttachmentEntityFidParams{
		HTTPClient: client,
	}
}

/*
PostAttachmentEntityFidParams contains all the parameters to send to the API endpoint

	for the post attachment entity fid operation.

	Typically these are written to a http.Request.
*/
type PostAttachmentEntityFidParams struct {

	/* EntityFid.

	   Entity FID to use
	*/
	EntityFid string

	// Payload.
	Payload *models.CreateAttachmentPayload

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post attachment entity fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAttachmentEntityFidParams) WithDefaults() *PostAttachmentEntityFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post attachment entity fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAttachmentEntityFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) WithTimeout(timeout time.Duration) *PostAttachmentEntityFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post attachment entity fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAttachmentEntityFidParams].
func (o *PostAttachmentEntityFidParams) WithContext(ctx context.Context) *PostAttachmentEntityFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post attachment entity fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAttachmentEntityFidParams].
func (o *PostAttachmentEntityFidParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) WithHTTPClient(client *http.Client) *PostAttachmentEntityFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEntityFid adds the entityFid to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) WithEntityFid(entityFid string) *PostAttachmentEntityFidParams {
	o.SetEntityFid(entityFid)
	return o
}

// SetEntityFid adds the entityFid to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) SetEntityFid(entityFid string) {
	o.EntityFid = entityFid
}

// WithPayload adds the payload to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) WithPayload(payload *models.CreateAttachmentPayload) *PostAttachmentEntityFidParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post attachment entity fid params.
func (o *PostAttachmentEntityFidParams) SetPayload(payload *models.CreateAttachmentPayload) {
	o.Payload = payload
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAttachmentEntityFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param entityFid
	if err := r.SetPathParam("entityFid", o.EntityFid); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
