// Code generated by go-swagger; DO NOT EDIT.

package flow

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// DeleteFlowsFlowFidStepsStepFidReader is a Reader for the DeleteFlowsFlowFidStepsStepFid structure.
type DeleteFlowsFlowFidStepsStepFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFlowsFlowFidStepsStepFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFlowsFlowFidStepsStepFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteFlowsFlowFidStepsStepFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteFlowsFlowFidStepsStepFidOK creates a DeleteFlowsFlowFidStepsStepFidOK with default headers values
func NewDeleteFlowsFlowFidStepsStepFidOK() *DeleteFlowsFlowFidStepsStepFidOK {
	return &DeleteFlowsFlowFidStepsStepFidOK{}
}

/*
DeleteFlowsFlowFidStepsStepFidOK describes a response with status code 200, with default header values.

Step archived successfully
*/
type DeleteFlowsFlowFidStepsStepFidOK struct {
	Payload *DeleteFlowsFlowFidStepsStepFidOKBody
}

// IsSuccess returns true when this delete flows flow fid steps step fid o k response has a 2xx status code
func (o *DeleteFlowsFlowFidStepsStepFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete flows flow fid steps step fid o k response has a 3xx status code
func (o *DeleteFlowsFlowFidStepsStepFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete flows flow fid steps step fid o k response has a 4xx status code
func (o *DeleteFlowsFlowFidStepsStepFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete flows flow fid steps step fid o k response has a 5xx status code
func (o *DeleteFlowsFlowFidStepsStepFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete flows flow fid steps step fid o k response a status code equal to that given
func (o *DeleteFlowsFlowFidStepsStepFidOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete flows flow fid steps step fid o k response
func (o *DeleteFlowsFlowFidStepsStepFidOK) Code() int {
	return 200
}

func (o *DeleteFlowsFlowFidStepsStepFidOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /flows/{flowFid}/steps/{stepFid}][%d] deleteFlowsFlowFidStepsStepFidOK %s", 200, payload)
}

func (o *DeleteFlowsFlowFidStepsStepFidOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /flows/{flowFid}/steps/{stepFid}][%d] deleteFlowsFlowFidStepsStepFidOK %s", 200, payload)
}

func (o *DeleteFlowsFlowFidStepsStepFidOK) GetPayload() *DeleteFlowsFlowFidStepsStepFidOKBody {
	return o.Payload
}

func (o *DeleteFlowsFlowFidStepsStepFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteFlowsFlowFidStepsStepFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteFlowsFlowFidStepsStepFidDefault creates a DeleteFlowsFlowFidStepsStepFidDefault with default headers values
func NewDeleteFlowsFlowFidStepsStepFidDefault(code int) *DeleteFlowsFlowFidStepsStepFidDefault {
	return &DeleteFlowsFlowFidStepsStepFidDefault{
		_statusCode: code,
	}
}

/*
DeleteFlowsFlowFidStepsStepFidDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteFlowsFlowFidStepsStepFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this delete flows flow fid steps step fid default response has a 2xx status code
func (o *DeleteFlowsFlowFidStepsStepFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete flows flow fid steps step fid default response has a 3xx status code
func (o *DeleteFlowsFlowFidStepsStepFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete flows flow fid steps step fid default response has a 4xx status code
func (o *DeleteFlowsFlowFidStepsStepFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete flows flow fid steps step fid default response has a 5xx status code
func (o *DeleteFlowsFlowFidStepsStepFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete flows flow fid steps step fid default response a status code equal to that given
func (o *DeleteFlowsFlowFidStepsStepFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete flows flow fid steps step fid default response
func (o *DeleteFlowsFlowFidStepsStepFidDefault) Code() int {
	return o._statusCode
}

func (o *DeleteFlowsFlowFidStepsStepFidDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /flows/{flowFid}/steps/{stepFid}][%d] DeleteFlowsFlowFidStepsStepFid default %s", o._statusCode, payload)
}

func (o *DeleteFlowsFlowFidStepsStepFidDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /flows/{flowFid}/steps/{stepFid}][%d] DeleteFlowsFlowFidStepsStepFid default %s", o._statusCode, payload)
}

func (o *DeleteFlowsFlowFidStepsStepFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *DeleteFlowsFlowFidStepsStepFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteFlowsFlowFidStepsStepFidOKBody delete flows flow fid steps step fid o k body
swagger:model DeleteFlowsFlowFidStepsStepFidOKBody
*/
type DeleteFlowsFlowFidStepsStepFidOKBody struct {
	models.Envelope

	// data
	Data *models.BoolMessage `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *DeleteFlowsFlowFidStepsStepFidOKBody) UnmarshalJSON(raw []byte) error {
	// DeleteFlowsFlowFidStepsStepFidOKBodyAO0
	var deleteFlowsFlowFidStepsStepFidOKBodyAO0 models.Envelope
	if err := jsonutils.ReadJSON(raw, &deleteFlowsFlowFidStepsStepFidOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = deleteFlowsFlowFidStepsStepFidOKBodyAO0

	// DeleteFlowsFlowFidStepsStepFidOKBodyAO1
	var dataDeleteFlowsFlowFidStepsStepFidOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}
	if err := jsonutils.ReadJSON(raw, &dataDeleteFlowsFlowFidStepsStepFidOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataDeleteFlowsFlowFidStepsStepFidOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o DeleteFlowsFlowFidStepsStepFidOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	deleteFlowsFlowFidStepsStepFidOKBodyAO0, err := jsonutils.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, deleteFlowsFlowFidStepsStepFidOKBodyAO0)
	var dataDeleteFlowsFlowFidStepsStepFidOKBodyAO1 struct {
		Data *models.BoolMessage `json:"data,omitempty"`
	}

	dataDeleteFlowsFlowFidStepsStepFidOKBodyAO1.Data = o.Data

	jsonDataDeleteFlowsFlowFidStepsStepFidOKBodyAO1, errDeleteFlowsFlowFidStepsStepFidOKBodyAO1 := jsonutils.WriteJSON(dataDeleteFlowsFlowFidStepsStepFidOKBodyAO1)
	if errDeleteFlowsFlowFidStepsStepFidOKBodyAO1 != nil {
		return nil, errDeleteFlowsFlowFidStepsStepFidOKBodyAO1
	}
	_parts = append(_parts, jsonDataDeleteFlowsFlowFidStepsStepFidOKBodyAO1)
	return jsonutils.ConcatJSON(_parts...), nil
}

// Validate validates this delete flows flow fid steps step fid o k body
func (o *DeleteFlowsFlowFidStepsStepFidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteFlowsFlowFidStepsStepFidOKBody) validateData(formats strfmt.Registry) error {

	if typeutils.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deleteFlowsFlowFidStepsStepFidOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deleteFlowsFlowFidStepsStepFidOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this delete flows flow fid steps step fid o k body based on the context it is used
func (o *DeleteFlowsFlowFidStepsStepFidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteFlowsFlowFidStepsStepFidOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if typeutils.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deleteFlowsFlowFidStepsStepFidOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deleteFlowsFlowFidStepsStepFidOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteFlowsFlowFidStepsStepFidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteFlowsFlowFidStepsStepFidOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteFlowsFlowFidStepsStepFidOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
