// Code generated by go-swagger; DO NOT EDIT.

package flow

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fortifi/go-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GetFlowsFlowFidReader is a Reader for the GetFlowsFlowFid structure.
type GetFlowsFlowFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFlowsFlowFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetFlowsFlowFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetFlowsFlowFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetFlowsFlowFidOK creates a GetFlowsFlowFidOK with default headers values
func NewGetFlowsFlowFidOK() *GetFlowsFlowFidOK {
	return &GetFlowsFlowFidOK{}
}

/*
GetFlowsFlowFidOK describes a response with status code 200, with default header values.

Flow details
*/
type GetFlowsFlowFidOK struct {
	Payload *GetFlowsFlowFidOKBody
}

// IsSuccess returns true when this get flows flow fid o k response has a 2xx status code
func (o *GetFlowsFlowFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get flows flow fid o k response has a 3xx status code
func (o *GetFlowsFlowFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get flows flow fid o k response has a 4xx status code
func (o *GetFlowsFlowFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get flows flow fid o k response has a 5xx status code
func (o *GetFlowsFlowFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get flows flow fid o k response a status code equal to that given
func (o *GetFlowsFlowFidOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get flows flow fid o k response
func (o *GetFlowsFlowFidOK) Code() int {
	return 200
}

func (o *GetFlowsFlowFidOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /flows/{flowFid}][%d] getFlowsFlowFidOK %s", 200, payload)
}

func (o *GetFlowsFlowFidOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /flows/{flowFid}][%d] getFlowsFlowFidOK %s", 200, payload)
}

func (o *GetFlowsFlowFidOK) GetPayload() *GetFlowsFlowFidOKBody {
	return o.Payload
}

func (o *GetFlowsFlowFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFlowsFlowFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetFlowsFlowFidDefault creates a GetFlowsFlowFidDefault with default headers values
func NewGetFlowsFlowFidDefault(code int) *GetFlowsFlowFidDefault {
	return &GetFlowsFlowFidDefault{
		_statusCode: code,
	}
}

/*
GetFlowsFlowFidDefault describes a response with status code -1, with default header values.

Error
*/
type GetFlowsFlowFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get flows flow fid default response has a 2xx status code
func (o *GetFlowsFlowFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get flows flow fid default response has a 3xx status code
func (o *GetFlowsFlowFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get flows flow fid default response has a 4xx status code
func (o *GetFlowsFlowFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get flows flow fid default response has a 5xx status code
func (o *GetFlowsFlowFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get flows flow fid default response a status code equal to that given
func (o *GetFlowsFlowFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get flows flow fid default response
func (o *GetFlowsFlowFidDefault) Code() int {
	return o._statusCode
}

func (o *GetFlowsFlowFidDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /flows/{flowFid}][%d] GetFlowsFlowFid default %s", o._statusCode, payload)
}

func (o *GetFlowsFlowFidDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /flows/{flowFid}][%d] GetFlowsFlowFid default %s", o._statusCode, payload)
}

func (o *GetFlowsFlowFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetFlowsFlowFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetFlowsFlowFidOKBody get flows flow fid o k body
swagger:model GetFlowsFlowFidOKBody
*/
type GetFlowsFlowFidOKBody struct {
	models.Envelope

	// data
	Data *models.Flow `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetFlowsFlowFidOKBody) UnmarshalJSON(raw []byte) error {
	// GetFlowsFlowFidOKBodyAO0
	var getFlowsFlowFidOKBodyAO0 models.Envelope
	if err := jsonutils.ReadJSON(raw, &getFlowsFlowFidOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getFlowsFlowFidOKBodyAO0

	// GetFlowsFlowFidOKBodyAO1
	var dataGetFlowsFlowFidOKBodyAO1 struct {
		Data *models.Flow `json:"data,omitempty"`
	}
	if err := jsonutils.ReadJSON(raw, &dataGetFlowsFlowFidOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetFlowsFlowFidOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetFlowsFlowFidOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getFlowsFlowFidOKBodyAO0, err := jsonutils.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getFlowsFlowFidOKBodyAO0)
	var dataGetFlowsFlowFidOKBodyAO1 struct {
		Data *models.Flow `json:"data,omitempty"`
	}

	dataGetFlowsFlowFidOKBodyAO1.Data = o.Data

	jsonDataGetFlowsFlowFidOKBodyAO1, errGetFlowsFlowFidOKBodyAO1 := jsonutils.WriteJSON(dataGetFlowsFlowFidOKBodyAO1)
	if errGetFlowsFlowFidOKBodyAO1 != nil {
		return nil, errGetFlowsFlowFidOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetFlowsFlowFidOKBodyAO1)
	return jsonutils.ConcatJSON(_parts...), nil
}

// Validate validates this get flows flow fid o k body
func (o *GetFlowsFlowFidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFlowsFlowFidOKBody) validateData(formats strfmt.Registry) error {

	if typeutils.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getFlowsFlowFidOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getFlowsFlowFidOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this get flows flow fid o k body based on the context it is used
func (o *GetFlowsFlowFidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFlowsFlowFidOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if typeutils.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getFlowsFlowFidOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getFlowsFlowFidOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetFlowsFlowFidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFlowsFlowFidOKBody) UnmarshalBinary(b []byte) error {
	var res GetFlowsFlowFidOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
