// Code generated by go-swagger; DO NOT EDIT.

package flow

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFlowsFlowFidStepsStepFidParams creates a new GetFlowsFlowFidStepsStepFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFlowsFlowFidStepsStepFidParams() *GetFlowsFlowFidStepsStepFidParams {
	return NewGetFlowsFlowFidStepsStepFidParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetFlowsFlowFidStepsStepFidParamsWithTimeout creates a new GetFlowsFlowFidStepsStepFidParams object
// with the ability to set a timeout on a request.
func NewGetFlowsFlowFidStepsStepFidParamsWithTimeout(timeout time.Duration) *GetFlowsFlowFidStepsStepFidParams {
	return &GetFlowsFlowFidStepsStepFidParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetFlowsFlowFidStepsStepFidParamsWithContext creates a new GetFlowsFlowFidStepsStepFidParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetFlowsFlowFidStepsStepFidParams].
func NewGetFlowsFlowFidStepsStepFidParamsWithContext(ctx context.Context) *GetFlowsFlowFidStepsStepFidParams {
	return &GetFlowsFlowFidStepsStepFidParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetFlowsFlowFidStepsStepFidParamsWithHTTPClient creates a new GetFlowsFlowFidStepsStepFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFlowsFlowFidStepsStepFidParamsWithHTTPClient(client *http.Client) *GetFlowsFlowFidStepsStepFidParams {
	return &GetFlowsFlowFidStepsStepFidParams{
		HTTPClient: client,
	}
}

/*
GetFlowsFlowFidStepsStepFidParams contains all the parameters to send to the API endpoint

	for the get flows flow fid steps step fid operation.

	Typically these are written to a http.Request.
*/
type GetFlowsFlowFidStepsStepFidParams struct {

	/* FlowFid.

	   Flow FID to use
	*/
	FlowFid string

	/* StepFid.

	   Flow Step FID to use
	*/
	StepFid string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get flows flow fid steps step fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFlowsFlowFidStepsStepFidParams) WithDefaults() *GetFlowsFlowFidStepsStepFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get flows flow fid steps step fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFlowsFlowFidStepsStepFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) WithTimeout(timeout time.Duration) *GetFlowsFlowFidStepsStepFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get flows flow fid steps step fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetFlowsFlowFidStepsStepFidParams].
func (o *GetFlowsFlowFidStepsStepFidParams) WithContext(ctx context.Context) *GetFlowsFlowFidStepsStepFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get flows flow fid steps step fid params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetFlowsFlowFidStepsStepFidParams].
func (o *GetFlowsFlowFidStepsStepFidParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) WithHTTPClient(client *http.Client) *GetFlowsFlowFidStepsStepFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFlowFid adds the flowFid to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) WithFlowFid(flowFid string) *GetFlowsFlowFidStepsStepFidParams {
	o.SetFlowFid(flowFid)
	return o
}

// SetFlowFid adds the flowFid to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) SetFlowFid(flowFid string) {
	o.FlowFid = flowFid
}

// WithStepFid adds the stepFid to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) WithStepFid(stepFid string) *GetFlowsFlowFidStepsStepFidParams {
	o.SetStepFid(stepFid)
	return o
}

// SetStepFid adds the stepFid to the get flows flow fid steps step fid params.
func (o *GetFlowsFlowFidStepsStepFidParams) SetStepFid(stepFid string) {
	o.StepFid = stepFid
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetFlowsFlowFidStepsStepFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param flowFid
	if err := r.SetPathParam("flowFid", o.FlowFid); err != nil {
		return err
	}

	// path param stepFid
	if err := r.SetPathParam("stepFid", o.StepFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
