// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new operations API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new operations API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for operations API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// PostCustomersCustomerFidApplyCredit apply credit to a customer.
	PostCustomersCustomerFidApplyCredit(params *PostCustomersCustomerFidApplyCreditParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidApplyCreditOK, error)

	// PostCustomersCustomerFidApplyCreditContext apply credit to a customer.
	PostCustomersCustomerFidApplyCreditContext(ctx context.Context, params *PostCustomersCustomerFidApplyCreditParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidApplyCreditOK, error)

	// PostCustomersCustomerFidPaymentMethodsCreatePending create a new pending payment method.
	PostCustomersCustomerFidPaymentMethodsCreatePending(params *PostCustomersCustomerFidPaymentMethodsCreatePendingParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidPaymentMethodsCreatePendingOK, error)

	// PostCustomersCustomerFidPaymentMethodsCreatePendingContext create a new pending payment method.
	PostCustomersCustomerFidPaymentMethodsCreatePendingContext(ctx context.Context, params *PostCustomersCustomerFidPaymentMethodsCreatePendingParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidPaymentMethodsCreatePendingOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
PostCustomersCustomerFidApplyCreditapplies credit to a customer.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostCustomersCustomerFidApplyCreditContext] instead.
*/
func (a *Client) PostCustomersCustomerFidApplyCredit(params *PostCustomersCustomerFidApplyCreditParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidApplyCreditOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostCustomersCustomerFidApplyCreditContext(ctx, params, authInfo, opts...)
}

/*
PostCustomersCustomerFidApplyCreditContextapplies credit to a customer.

Do not use the deprecated [PostCustomersCustomerFidApplyCreditParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostCustomersCustomerFidApplyCreditContext(ctx context.Context, params *PostCustomersCustomerFidApplyCreditParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidApplyCreditOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostCustomersCustomerFidApplyCreditParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostCustomersCustomerFidApplyCredit",
		Method:             "POST",
		PathPattern:        "/customers/{customerFid}/applyCredit",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostCustomersCustomerFidApplyCreditReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostCustomersCustomerFidApplyCreditOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostCustomersCustomerFidApplyCreditDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostCustomersCustomerFidPaymentMethodsCreatePendingcreates a new pending payment method.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostCustomersCustomerFidPaymentMethodsCreatePendingContext] instead.
*/
func (a *Client) PostCustomersCustomerFidPaymentMethodsCreatePending(params *PostCustomersCustomerFidPaymentMethodsCreatePendingParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidPaymentMethodsCreatePendingOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostCustomersCustomerFidPaymentMethodsCreatePendingContext(ctx, params, authInfo, opts...)
}

/*
PostCustomersCustomerFidPaymentMethodsCreatePendingContextcreates a new pending payment method.

Do not use the deprecated [PostCustomersCustomerFidPaymentMethodsCreatePendingParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostCustomersCustomerFidPaymentMethodsCreatePendingContext(ctx context.Context, params *PostCustomersCustomerFidPaymentMethodsCreatePendingParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCustomersCustomerFidPaymentMethodsCreatePendingOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostCustomersCustomerFidPaymentMethodsCreatePendingParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostCustomersCustomerFidPaymentMethodsCreatePending",
		Method:             "POST",
		PathPattern:        "/customers/{customerFid}/paymentMethods/createPending",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostCustomersCustomerFidPaymentMethodsCreatePendingReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostCustomersCustomerFidPaymentMethodsCreatePendingOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostCustomersCustomerFidPaymentMethodsCreatePendingDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [OperationsParams].
	ctx context.Context
}
