// Code generated by go-swagger; DO NOT EDIT.

package interactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInteractionsInteractionFidMessageParams creates a new GetInteractionsInteractionFidMessageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInteractionsInteractionFidMessageParams() *GetInteractionsInteractionFidMessageParams {
	return &GetInteractionsInteractionFidMessageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInteractionsInteractionFidMessageParamsWithTimeout creates a new GetInteractionsInteractionFidMessageParams object
// with the ability to set a timeout on a request.
func NewGetInteractionsInteractionFidMessageParamsWithTimeout(timeout time.Duration) *GetInteractionsInteractionFidMessageParams {
	return &GetInteractionsInteractionFidMessageParams{
		timeout: timeout,
	}
}

// NewGetInteractionsInteractionFidMessageParamsWithContext creates a new GetInteractionsInteractionFidMessageParams object
// with the ability to set a context for a request.
func NewGetInteractionsInteractionFidMessageParamsWithContext(ctx context.Context) *GetInteractionsInteractionFidMessageParams {
	return &GetInteractionsInteractionFidMessageParams{
		Context: ctx,
	}
}

// NewGetInteractionsInteractionFidMessageParamsWithHTTPClient creates a new GetInteractionsInteractionFidMessageParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInteractionsInteractionFidMessageParamsWithHTTPClient(client *http.Client) *GetInteractionsInteractionFidMessageParams {
	return &GetInteractionsInteractionFidMessageParams{
		HTTPClient: client,
	}
}

/*
GetInteractionsInteractionFidMessageParams contains all the parameters to send to the API endpoint

	for the get interactions interaction fid message operation.

	Typically these are written to a http.Request.
*/
type GetInteractionsInteractionFidMessageParams struct {

	// InteractionFid.
	InteractionFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get interactions interaction fid message params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInteractionsInteractionFidMessageParams) WithDefaults() *GetInteractionsInteractionFidMessageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get interactions interaction fid message params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInteractionsInteractionFidMessageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) WithTimeout(timeout time.Duration) *GetInteractionsInteractionFidMessageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) WithContext(ctx context.Context) *GetInteractionsInteractionFidMessageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) WithHTTPClient(client *http.Client) *GetInteractionsInteractionFidMessageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInteractionFid adds the interactionFid to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) WithInteractionFid(interactionFid string) *GetInteractionsInteractionFidMessageParams {
	o.SetInteractionFid(interactionFid)
	return o
}

// SetInteractionFid adds the interactionFid to the get interactions interaction fid message params
func (o *GetInteractionsInteractionFidMessageParams) SetInteractionFid(interactionFid string) {
	o.InteractionFid = interactionFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetInteractionsInteractionFidMessageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param interactionFid
	if err := r.SetPathParam("interactionFid", o.InteractionFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
