// Code generated by go-swagger; DO NOT EDIT.

package interactions

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new interactions API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new interactions API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new interactions API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for interactions API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetInteractionsInteractionFid get an interaction.
	GetInteractionsInteractionFid(params *GetInteractionsInteractionFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidOK, error)

	// GetInteractionsInteractionFidContext get an interaction.
	GetInteractionsInteractionFidContext(ctx context.Context, params *GetInteractionsInteractionFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidOK, error)

	// GetInteractionsInteractionFidMessages get all messages on an interaction.
	GetInteractionsInteractionFidMessages(params *GetInteractionsInteractionFidMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidMessagesOK, error)

	// GetInteractionsInteractionFidMessagesContext get all messages on an interaction.
	GetInteractionsInteractionFidMessagesContext(ctx context.Context, params *GetInteractionsInteractionFidMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidMessagesOK, error)

	// GetInteractionsInviteInviteCodeStatus get an interaction invite status.
	GetInteractionsInviteInviteCodeStatus(params *GetInteractionsInviteInviteCodeStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInviteInviteCodeStatusOK, error)

	// GetInteractionsInviteInviteCodeStatusContext get an interaction invite status.
	GetInteractionsInviteInviteCodeStatusContext(ctx context.Context, params *GetInteractionsInviteInviteCodeStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInviteInviteCodeStatusOK, error)

	// PostInteractionsInteractionFidAttachment create an interaction attachment.
	PostInteractionsInteractionFidAttachment(params *PostInteractionsInteractionFidAttachmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidAttachmentOK, error)

	// PostInteractionsInteractionFidAttachmentContext create an interaction attachment.
	PostInteractionsInteractionFidAttachmentContext(ctx context.Context, params *PostInteractionsInteractionFidAttachmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidAttachmentOK, error)

	// PostInteractionsInteractionFidClientConnected a client has connected to the interaction.
	PostInteractionsInteractionFidClientConnected(params *PostInteractionsInteractionFidClientConnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientConnectedOK, error)

	// PostInteractionsInteractionFidClientConnectedContext a client has connected to the interaction.
	PostInteractionsInteractionFidClientConnectedContext(ctx context.Context, params *PostInteractionsInteractionFidClientConnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientConnectedOK, error)

	// PostInteractionsInteractionFidClientDisconnected a client has disconnected from the interaction.
	PostInteractionsInteractionFidClientDisconnected(params *PostInteractionsInteractionFidClientDisconnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientDisconnectedOK, error)

	// PostInteractionsInteractionFidClientDisconnectedContext a client has disconnected from the interaction.
	PostInteractionsInteractionFidClientDisconnectedContext(ctx context.Context, params *PostInteractionsInteractionFidClientDisconnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientDisconnectedOK, error)

	// PostInteractionsInteractionFidCustomerClosed the customer has purposely closed the interaction.
	PostInteractionsInteractionFidCustomerClosed(params *PostInteractionsInteractionFidCustomerClosedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidCustomerClosedOK, error)

	// PostInteractionsInteractionFidCustomerClosedContext the customer has purposely closed the interaction.
	PostInteractionsInteractionFidCustomerClosedContext(ctx context.Context, params *PostInteractionsInteractionFidCustomerClosedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidCustomerClosedOK, error)

	// PostInteractionsInteractionFidFeedback submit feedback to an interaction.
	PostInteractionsInteractionFidFeedback(params *PostInteractionsInteractionFidFeedbackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidFeedbackOK, error)

	// PostInteractionsInteractionFidFeedbackContext submit feedback to an interaction.
	PostInteractionsInteractionFidFeedbackContext(ctx context.Context, params *PostInteractionsInteractionFidFeedbackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidFeedbackOK, error)

	// PostInteractionsInteractionFidMessage add a message to a interaction.
	PostInteractionsInteractionFidMessage(params *PostInteractionsInteractionFidMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidMessageOK, error)

	// PostInteractionsInteractionFidMessageContext add a message to a interaction.
	PostInteractionsInteractionFidMessageContext(ctx context.Context, params *PostInteractionsInteractionFidMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidMessageOK, error)

	// PostInteractionsInteractionFidSendChatTranscript send a chat transcript to the customer email.
	PostInteractionsInteractionFidSendChatTranscript(params *PostInteractionsInteractionFidSendChatTranscriptParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidSendChatTranscriptOK, error)

	// PostInteractionsInteractionFidSendChatTranscriptContext send a chat transcript to the customer email.
	PostInteractionsInteractionFidSendChatTranscriptContext(ctx context.Context, params *PostInteractionsInteractionFidSendChatTranscriptParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidSendChatTranscriptOK, error)

	// PostInteractionsInvite create an interaction invite.
	PostInteractionsInvite(params *PostInteractionsInviteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteOK, error)

	// PostInteractionsInviteContext create an interaction invite.
	PostInteractionsInviteContext(ctx context.Context, params *PostInteractionsInviteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteOK, error)

	// PostInteractionsInviteInviteCode accept an interaction invite.
	PostInteractionsInviteInviteCode(params *PostInteractionsInviteInviteCodeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteInviteCodeOK, error)

	// PostInteractionsInviteInviteCodeContext accept an interaction invite.
	PostInteractionsInviteInviteCodeContext(ctx context.Context, params *PostInteractionsInviteInviteCodeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteInviteCodeOK, error)

	// PostInteractionsJourney create a customer journey.
	PostInteractionsJourney(params *PostInteractionsJourneyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsJourneyOK, error)

	// PostInteractionsJourneyContext create a customer journey.
	PostInteractionsJourneyContext(ctx context.Context, params *PostInteractionsJourneyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsJourneyOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
GetInteractionsInteractionFidgets an interaction.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetInteractionsInteractionFidContext] instead.
*/
func (a *Client) GetInteractionsInteractionFid(params *GetInteractionsInteractionFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetInteractionsInteractionFidContext(ctx, params, authInfo, opts...)
}

/*
GetInteractionsInteractionFidContextgets an interaction.

Do not use the deprecated [GetInteractionsInteractionFidParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetInteractionsInteractionFidContext(ctx context.Context, params *GetInteractionsInteractionFidParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetInteractionsInteractionFidParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetInteractionsInteractionFid",
		Method:             "GET",
		PathPattern:        "/interactions/{interactionFid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInteractionsInteractionFidReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetInteractionsInteractionFidOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetInteractionsInteractionFidDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetInteractionsInteractionFidMessagesgets all messages on an interaction.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetInteractionsInteractionFidMessagesContext] instead.
*/
func (a *Client) GetInteractionsInteractionFidMessages(params *GetInteractionsInteractionFidMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidMessagesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetInteractionsInteractionFidMessagesContext(ctx, params, authInfo, opts...)
}

/*
GetInteractionsInteractionFidMessagesContextgets all messages on an interaction.

Do not use the deprecated [GetInteractionsInteractionFidMessagesParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetInteractionsInteractionFidMessagesContext(ctx context.Context, params *GetInteractionsInteractionFidMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInteractionFidMessagesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetInteractionsInteractionFidMessagesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetInteractionsInteractionFidMessages",
		Method:             "GET",
		PathPattern:        "/interactions/{interactionFid}/messages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInteractionsInteractionFidMessagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetInteractionsInteractionFidMessagesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetInteractionsInteractionFidMessagesDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetInteractionsInviteInviteCodeStatusgets an interaction invite status.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetInteractionsInviteInviteCodeStatusContext] instead.
*/
func (a *Client) GetInteractionsInviteInviteCodeStatus(params *GetInteractionsInviteInviteCodeStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInviteInviteCodeStatusOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetInteractionsInviteInviteCodeStatusContext(ctx, params, authInfo, opts...)
}

/*
GetInteractionsInviteInviteCodeStatusContextgets an interaction invite status.

Do not use the deprecated [GetInteractionsInviteInviteCodeStatusParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetInteractionsInviteInviteCodeStatusContext(ctx context.Context, params *GetInteractionsInviteInviteCodeStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetInteractionsInviteInviteCodeStatusOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetInteractionsInviteInviteCodeStatusParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetInteractionsInviteInviteCodeStatus",
		Method:             "GET",
		PathPattern:        "/interactions/invite/{inviteCode}/status",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInteractionsInviteInviteCodeStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetInteractionsInviteInviteCodeStatusOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetInteractionsInviteInviteCodeStatusDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInteractionFidAttachmentcreates an interaction attachment.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInteractionFidAttachmentContext] instead.
*/
func (a *Client) PostInteractionsInteractionFidAttachment(params *PostInteractionsInteractionFidAttachmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidAttachmentOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInteractionFidAttachmentContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInteractionFidAttachmentContextcreates an interaction attachment.

Do not use the deprecated [PostInteractionsInteractionFidAttachmentParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInteractionFidAttachmentContext(ctx context.Context, params *PostInteractionsInteractionFidAttachmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidAttachmentOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInteractionFidAttachmentParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInteractionFidAttachment",
		Method:             "POST",
		PathPattern:        "/interactions/{interactionFid}/attachment",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInteractionFidAttachmentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInteractionFidAttachmentOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInteractionFidAttachmentDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInteractionFidClientConnectedas client has connected to the interaction.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInteractionFidClientConnectedContext] instead.
*/
func (a *Client) PostInteractionsInteractionFidClientConnected(params *PostInteractionsInteractionFidClientConnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientConnectedOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInteractionFidClientConnectedContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInteractionFidClientConnectedContextas client has connected to the interaction.

Do not use the deprecated [PostInteractionsInteractionFidClientConnectedParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInteractionFidClientConnectedContext(ctx context.Context, params *PostInteractionsInteractionFidClientConnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientConnectedOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInteractionFidClientConnectedParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInteractionFidClientConnected",
		Method:             "POST",
		PathPattern:        "/interactions/{interactionFid}/client/connected",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInteractionFidClientConnectedReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInteractionFidClientConnectedOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInteractionFidClientConnectedDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInteractionFidClientDisconnectedas client has disconnected from the interaction.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInteractionFidClientDisconnectedContext] instead.
*/
func (a *Client) PostInteractionsInteractionFidClientDisconnected(params *PostInteractionsInteractionFidClientDisconnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientDisconnectedOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInteractionFidClientDisconnectedContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInteractionFidClientDisconnectedContextas client has disconnected from the interaction.

Do not use the deprecated [PostInteractionsInteractionFidClientDisconnectedParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInteractionFidClientDisconnectedContext(ctx context.Context, params *PostInteractionsInteractionFidClientDisconnectedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidClientDisconnectedOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInteractionFidClientDisconnectedParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInteractionFidClientDisconnected",
		Method:             "POST",
		PathPattern:        "/interactions/{interactionFid}/client/disconnected",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInteractionFidClientDisconnectedReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInteractionFidClientDisconnectedOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInteractionFidClientDisconnectedDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInteractionFidCustomerClosedthes customer has purposely closed the interaction.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInteractionFidCustomerClosedContext] instead.
*/
func (a *Client) PostInteractionsInteractionFidCustomerClosed(params *PostInteractionsInteractionFidCustomerClosedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidCustomerClosedOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInteractionFidCustomerClosedContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInteractionFidCustomerClosedContextthes customer has purposely closed the interaction.

Do not use the deprecated [PostInteractionsInteractionFidCustomerClosedParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInteractionFidCustomerClosedContext(ctx context.Context, params *PostInteractionsInteractionFidCustomerClosedParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidCustomerClosedOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInteractionFidCustomerClosedParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInteractionFidCustomerClosed",
		Method:             "POST",
		PathPattern:        "/interactions/{interactionFid}/customerClosed",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInteractionFidCustomerClosedReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInteractionFidCustomerClosedOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInteractionFidCustomerClosedDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInteractionFidFeedbacksubmits feedback to an interaction.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInteractionFidFeedbackContext] instead.
*/
func (a *Client) PostInteractionsInteractionFidFeedback(params *PostInteractionsInteractionFidFeedbackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidFeedbackOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInteractionFidFeedbackContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInteractionFidFeedbackContextsubmits feedback to an interaction.

Do not use the deprecated [PostInteractionsInteractionFidFeedbackParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInteractionFidFeedbackContext(ctx context.Context, params *PostInteractionsInteractionFidFeedbackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidFeedbackOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInteractionFidFeedbackParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInteractionFidFeedback",
		Method:             "POST",
		PathPattern:        "/interactions/{interactionFid}/feedback",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInteractionFidFeedbackReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInteractionFidFeedbackOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInteractionFidFeedbackDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInteractionFidMessageadds a message to a interaction.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInteractionFidMessageContext] instead.
*/
func (a *Client) PostInteractionsInteractionFidMessage(params *PostInteractionsInteractionFidMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidMessageOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInteractionFidMessageContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInteractionFidMessageContextadds a message to a interaction.

Do not use the deprecated [PostInteractionsInteractionFidMessageParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInteractionFidMessageContext(ctx context.Context, params *PostInteractionsInteractionFidMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidMessageOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInteractionFidMessageParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInteractionFidMessage",
		Method:             "POST",
		PathPattern:        "/interactions/{interactionFid}/message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInteractionFidMessageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInteractionFidMessageOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInteractionFidMessageDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInteractionFidSendChatTranscriptsends a chat transcript to the customer email.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInteractionFidSendChatTranscriptContext] instead.
*/
func (a *Client) PostInteractionsInteractionFidSendChatTranscript(params *PostInteractionsInteractionFidSendChatTranscriptParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidSendChatTranscriptOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInteractionFidSendChatTranscriptContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInteractionFidSendChatTranscriptContextsends a chat transcript to the customer email.

Do not use the deprecated [PostInteractionsInteractionFidSendChatTranscriptParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInteractionFidSendChatTranscriptContext(ctx context.Context, params *PostInteractionsInteractionFidSendChatTranscriptParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInteractionFidSendChatTranscriptOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInteractionFidSendChatTranscriptParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInteractionFidSendChatTranscript",
		Method:             "POST",
		PathPattern:        "/interactions/{interactionFid}/sendChatTranscript",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInteractionFidSendChatTranscriptReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInteractionFidSendChatTranscriptOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInteractionFidSendChatTranscriptDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInvitecreates an interaction invite.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInviteContext] instead.
*/
func (a *Client) PostInteractionsInvite(params *PostInteractionsInviteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInviteContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInviteContextcreates an interaction invite.

Do not use the deprecated [PostInteractionsInviteParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInviteContext(ctx context.Context, params *PostInteractionsInviteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInviteParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInvite",
		Method:             "POST",
		PathPattern:        "/interactions/invite",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInviteReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInviteOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInviteDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsInviteInviteCodeaccepts an interaction invite.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsInviteInviteCodeContext] instead.
*/
func (a *Client) PostInteractionsInviteInviteCode(params *PostInteractionsInviteInviteCodeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteInviteCodeOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsInviteInviteCodeContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsInviteInviteCodeContextaccepts an interaction invite.

Do not use the deprecated [PostInteractionsInviteInviteCodeParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsInviteInviteCodeContext(ctx context.Context, params *PostInteractionsInviteInviteCodeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsInviteInviteCodeOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsInviteInviteCodeParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsInviteInviteCode",
		Method:             "POST",
		PathPattern:        "/interactions/invite/{inviteCode}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsInviteInviteCodeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsInviteInviteCodeOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsInviteInviteCodeDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostInteractionsJourneycreates a customer journey.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostInteractionsJourneyContext] instead.
*/
func (a *Client) PostInteractionsJourney(params *PostInteractionsJourneyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsJourneyOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostInteractionsJourneyContext(ctx, params, authInfo, opts...)
}

/*
PostInteractionsJourneyContextcreates a customer journey.

Do not use the deprecated [PostInteractionsJourneyParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostInteractionsJourneyContext(ctx context.Context, params *PostInteractionsJourneyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostInteractionsJourneyOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostInteractionsJourneyParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostInteractionsJourney",
		Method:             "POST",
		PathPattern:        "/interactions/journey",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostInteractionsJourneyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostInteractionsJourneyOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PostInteractionsJourneyDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [InteractionsParams].
	ctx context.Context
}
