// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ChatSessionsAllOf1 chat sessions all of1
// swagger:model chatSessionsAllOf1
type ChatSessionsAllOf1 struct {

	// chat sessions
	ChatSessions ChatSessionsAllOf1ChatSessions `json:"chatSessions"`
}

// Validate validates this chat sessions all of1
func (m *ChatSessionsAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ChatSessionsAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatSessionsAllOf1) UnmarshalBinary(b []byte) error {
	var res ChatSessionsAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
