// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateProductSkuPayload create product sku payload
//
// swagger:model CreateProductSkuPayload
type CreateProductSkuPayload struct {

	// description
	Description string `json:"description,omitempty"`

	// display name
	// Max Length: 60
	DisplayName string `json:"displayName,omitempty"`

	// price band fid
	// Max Length: 64
	PriceBandFid string `json:"priceBandFid,omitempty"`

	// sku
	// Max Length: 120
	Sku string `json:"sku,omitempty"`
}

// Validate validates this create product sku payload
func (m *CreateProductSkuPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriceBandFid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSku(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateProductSkuPayload) validateDisplayName(formats strfmt.Registry) error {
	if swag.IsZero(m.DisplayName) { // not required
		return nil
	}

	if err := validate.MaxLength("displayName", "body", m.DisplayName, 60); err != nil {
		return err
	}

	return nil
}

func (m *CreateProductSkuPayload) validatePriceBandFid(formats strfmt.Registry) error {
	if swag.IsZero(m.PriceBandFid) { // not required
		return nil
	}

	if err := validate.MaxLength("priceBandFid", "body", m.PriceBandFid, 64); err != nil {
		return err
	}

	return nil
}

func (m *CreateProductSkuPayload) validateSku(formats strfmt.Registry) error {
	if swag.IsZero(m.Sku) { // not required
		return nil
	}

	if err := validate.MaxLength("sku", "body", m.Sku, 120); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create product sku payload based on context it is used
func (m *CreateProductSkuPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateProductSkuPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateProductSkuPayload) UnmarshalBinary(b []byte) error {
	var res CreateProductSkuPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
