// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateProductGroupPayload create product group payload
//
// swagger:model CreateProductGroupPayload
type CreateProductGroupPayload struct {

	// description
	Description string `json:"description,omitempty"`

	// display name
	// Max Length: 60
	DisplayName string `json:"displayName,omitempty"`

	// group type
	// Maximum: 255
	GroupType int32 `json:"groupType,omitempty"`
}

// Validate validates this create product group payload
func (m *CreateProductGroupPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateProductGroupPayload) validateDisplayName(formats strfmt.Registry) error {
	if swag.IsZero(m.DisplayName) { // not required
		return nil
	}

	if err := validate.MaxLength("displayName", "body", m.DisplayName, 60); err != nil {
		return err
	}

	return nil
}

func (m *CreateProductGroupPayload) validateGroupType(formats strfmt.Registry) error {
	if swag.IsZero(m.GroupType) { // not required
		return nil
	}

	if err := validate.MaximumInt("groupType", "body", int64(m.GroupType), 255, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create product group payload based on context it is used
func (m *CreateProductGroupPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateProductGroupPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateProductGroupPayload) UnmarshalBinary(b []byte) error {
	var res CreateProductGroupPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
