// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreditNote Credit note information
//
// swagger:model CreditNote
type CreditNote struct {

	// amount
	Amount float32 `json:"amount,omitempty"`

	// credit note fid
	CreditNoteFid string `json:"creditNoteFid,omitempty"`

	// credit note reason
	CreditNoteReason string `json:"creditNoteReason,omitempty"`

	// credit note type
	CreditNoteType string `json:"creditNoteType,omitempty"`

	// currency
	Currency string `json:"currency,omitempty"`

	// Time in ISO 8601 standard with optional fractions of a second e.g 2015-12-05T13:11:59.888Z
	// Format: date-time
	DateCreated strfmt.DateTime `json:"dateCreated,omitempty"`
}

// Validate validates this credit note
func (m *CreditNote) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateCreated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreditNote) validateDateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.DateCreated) { // not required
		return nil
	}

	if err := validate.FormatOf("dateCreated", "body", "date-time", m.DateCreated.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this credit note based on context it is used
func (m *CreditNote) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreditNote) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreditNote) UnmarshalBinary(b []byte) error {
	var res CreditNote
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
