// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FlowLogMetricPayload Flow Log Metric
//
// swagger:model FlowLogMetricPayload
type FlowLogMetricPayload struct {

	// action
	// Required: true
	Action *string `json:"action"`

	// action timestamp
	ActionTimestamp int64 `json:"actionTimestamp,omitempty"`

	// amount
	Amount string `json:"amount,omitempty"`

	// FID of a valid Brand
	BrandFid string `json:"brandFid,omitempty"`

	// Advertiser Campaign to track this action to (if not already locked)
	//
	CampaignHash string `json:"campaignHash,omitempty"`

	// IP Address of the visitor
	ClientIP string `json:"clientIp,omitempty"`

	// Customer FID linked to this action
	CustomerFid string `json:"customerFid,omitempty"`

	// Encoding from the visitors browser 'HTTP_ACCEPT_ENCODING'
	Encoding string `json:"encoding,omitempty"`

	// Language from visitors browser 'HTTP_ACCEPT_LANGUAGE'
	Language string `json:"language,omitempty"`

	// offer fid
	OfferFid string `json:"offerFid,omitempty"`

	// purchase fid
	PurchaseFid string `json:"purchaseFid,omitempty"`

	// purchase segment
	PurchaseSegment string `json:"purchaseSegment,omitempty"`

	// session Id
	// Required: true
	SessionID *string `json:"sessionId"`

	// Advertiser sub tracking ID 1
	Sid1 string `json:"sid1,omitempty"`

	// Advertiser sub tracking ID 2
	Sid2 string `json:"sid2,omitempty"`

	// Advertiser sub tracking ID 3
	Sid3 string `json:"sid3,omitempty"`

	// Source of the action
	Source string `json:"source,omitempty"`

	// User Agent of the visitors browser 'HTTP_USER_AGENT'
	UserAgent string `json:"userAgent,omitempty"`
}

// Validate validates this flow log metric payload
func (m *FlowLogMetricPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FlowLogMetricPayload) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	return nil
}

func (m *FlowLogMetricPayload) validateSessionID(formats strfmt.Registry) error {

	if err := validate.Required("sessionId", "body", m.SessionID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this flow log metric payload based on context it is used
func (m *FlowLogMetricPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FlowLogMetricPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FlowLogMetricPayload) UnmarshalBinary(b []byte) error {
	var res FlowLogMetricPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
