// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OfferPriceResponse Offer price breakdown (post-discount)
//
// swagger:model OfferPriceResponse
type OfferPriceResponse struct {

	// total discount gross amount
	TotalDiscountGrossAmount float32 `json:"totalDiscountGrossAmount,omitempty"`

	// total discount net amount
	TotalDiscountNetAmount float32 `json:"totalDiscountNetAmount,omitempty"`

	// total discount tax amount
	TotalDiscountTaxAmount float32 `json:"totalDiscountTaxAmount,omitempty"`

	// total gross amount
	TotalGrossAmount float32 `json:"totalGrossAmount,omitempty"`

	// total net amount
	TotalNetAmount float32 `json:"totalNetAmount,omitempty"`

	// total tax amount
	TotalTaxAmount float32 `json:"totalTaxAmount,omitempty"`

	// unit discount gross amount
	UnitDiscountGrossAmount float32 `json:"unitDiscountGrossAmount,omitempty"`

	// unit discount net amount
	UnitDiscountNetAmount float32 `json:"unitDiscountNetAmount,omitempty"`

	// unit discount tax amount
	UnitDiscountTaxAmount float32 `json:"unitDiscountTaxAmount,omitempty"`

	// unit gross amount
	UnitGrossAmount float32 `json:"unitGrossAmount,omitempty"`

	// unit net amount
	UnitNetAmount float32 `json:"unitNetAmount,omitempty"`

	// unit tax amount
	UnitTaxAmount float32 `json:"unitTaxAmount,omitempty"`
}

// Validate validates this offer price response
func (m *OfferPriceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this offer price response based on context it is used
func (m *OfferPriceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OfferPriceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OfferPriceResponse) UnmarshalBinary(b []byte) error {
	var res OfferPriceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
