// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderVerification Generic Response
//
// swagger:model OrderVerification
type OrderVerification struct {

	// redirect Url
	RedirectURL string `json:"redirectUrl,omitempty"`

	// require redirect
	RequireRedirect bool `json:"requireRedirect,omitempty"`
}

// Validate validates this order verification
func (m *OrderVerification) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this order verification based on context it is used
func (m *OrderVerification) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderVerification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderVerification) UnmarshalBinary(b []byte) error {
	var res OrderVerification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
