// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PubKey Generic Response
//
// swagger:model PubKey
type PubKey struct {

	// RSA Public Key
	Key string `json:"key,omitempty"`
}

// Validate validates this pub key
func (m *PubKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pub key based on context it is used
func (m *PubKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PubKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PubKey) UnmarshalBinary(b []byte) error {
	var res PubKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
