// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SetCustomerLocationPayload set customer location payload
//
// swagger:model SetCustomerLocationPayload
type SetCustomerLocationPayload struct {

	// City
	City string `json:"city,omitempty"`

	// Client IP Address
	ClientIP string `json:"clientIp,omitempty"`

	// Continent
	Continent string `json:"continent,omitempty"`

	// Country
	Country string `json:"country,omitempty"`

	// County
	County string `json:"county,omitempty"`

	// Postal
	Postal string `json:"postal,omitempty"`

	// Timezone
	Timezone string `json:"timezone,omitempty"`
}

// Validate validates this set customer location payload
func (m *SetCustomerLocationPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set customer location payload based on context it is used
func (m *SetCustomerLocationPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetCustomerLocationPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetCustomerLocationPayload) UnmarshalBinary(b []byte) error {
	var res SetCustomerLocationPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
