// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SubscriptionCancellation Generic Response
//
// swagger:model SubscriptionCancellation
type SubscriptionCancellation struct {
	Subscription

	// amount with tax
	AmountWithTax float32 `json:"amountWithTax,omitempty"`

	// amount without tax
	AmountWithoutTax float32 `json:"amountWithoutTax,omitempty"`

	// tax
	Tax float32 `json:"tax,omitempty"`

	// termination fee
	TerminationFee float32 `json:"terminationFee,omitempty"`

	// termination fee with tax
	TerminationFeeWithTax float32 `json:"terminationFeeWithTax,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SubscriptionCancellation) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Subscription
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Subscription = aO0

	// AO1
	var dataAO1 struct {
		AmountWithTax float32 `json:"amountWithTax,omitempty"`

		AmountWithoutTax float32 `json:"amountWithoutTax,omitempty"`

		Tax float32 `json:"tax,omitempty"`

		TerminationFee float32 `json:"terminationFee,omitempty"`

		TerminationFeeWithTax float32 `json:"terminationFeeWithTax,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.AmountWithTax = dataAO1.AmountWithTax

	m.AmountWithoutTax = dataAO1.AmountWithoutTax

	m.Tax = dataAO1.Tax

	m.TerminationFee = dataAO1.TerminationFee

	m.TerminationFeeWithTax = dataAO1.TerminationFeeWithTax

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SubscriptionCancellation) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Subscription)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		AmountWithTax float32 `json:"amountWithTax,omitempty"`

		AmountWithoutTax float32 `json:"amountWithoutTax,omitempty"`

		Tax float32 `json:"tax,omitempty"`

		TerminationFee float32 `json:"terminationFee,omitempty"`

		TerminationFeeWithTax float32 `json:"terminationFeeWithTax,omitempty"`
	}

	dataAO1.AmountWithTax = m.AmountWithTax

	dataAO1.AmountWithoutTax = m.AmountWithoutTax

	dataAO1.Tax = m.Tax

	dataAO1.TerminationFee = m.TerminationFee

	dataAO1.TerminationFeeWithTax = m.TerminationFeeWithTax

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this subscription cancellation
func (m *SubscriptionCancellation) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Subscription
	if err := m.Subscription.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this subscription cancellation based on the context it is used
func (m *SubscriptionCancellation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Subscription
	if err := m.Subscription.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionCancellation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionCancellation) UnmarshalBinary(b []byte) error {
	var res SubscriptionCancellation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
