// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// TaxItemBreakdownResponse Tax Item Response with per-item base/offer price breakdown
//
// swagger:model TaxItemBreakdownResponse
type TaxItemBreakdownResponse struct {
	TaxItemResponse

	// base price
	BasePrice *BasePriceResponse `json:"basePrice,omitempty"`

	// offer price
	OfferPrice *OfferPriceResponse `json:"offerPrice,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TaxItemBreakdownResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TaxItemResponse
	if err := jsonutils.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TaxItemResponse = aO0

	// AO1
	var dataAO1 struct {
		BasePrice *BasePriceResponse `json:"basePrice,omitempty"`

		OfferPrice *OfferPriceResponse `json:"offerPrice,omitempty"`
	}
	if err := jsonutils.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.BasePrice = dataAO1.BasePrice

	m.OfferPrice = dataAO1.OfferPrice

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TaxItemBreakdownResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := jsonutils.WriteJSON(m.TaxItemResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		BasePrice *BasePriceResponse `json:"basePrice,omitempty"`

		OfferPrice *OfferPriceResponse `json:"offerPrice,omitempty"`
	}

	dataAO1.BasePrice = m.BasePrice

	dataAO1.OfferPrice = m.OfferPrice

	jsonDataAO1, errAO1 := jsonutils.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return jsonutils.ConcatJSON(_parts...), nil
}

// Validate validates this tax item breakdown response
func (m *TaxItemBreakdownResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TaxItemResponse
	if err := m.TaxItemResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBasePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOfferPrice(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaxItemBreakdownResponse) validateBasePrice(formats strfmt.Registry) error {

	if typeutils.IsZero(m.BasePrice) { // not required
		return nil
	}

	if m.BasePrice != nil {
		if err := m.BasePrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("basePrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("basePrice")
			}

			return err
		}
	}

	return nil
}

func (m *TaxItemBreakdownResponse) validateOfferPrice(formats strfmt.Registry) error {

	if typeutils.IsZero(m.OfferPrice) { // not required
		return nil
	}

	if m.OfferPrice != nil {
		if err := m.OfferPrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("offerPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("offerPrice")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this tax item breakdown response based on the context it is used
func (m *TaxItemBreakdownResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TaxItemResponse
	if err := m.TaxItemResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBasePrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOfferPrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaxItemBreakdownResponse) contextValidateBasePrice(ctx context.Context, formats strfmt.Registry) error {

	if m.BasePrice != nil {

		if typeutils.IsZero(m.BasePrice) { // not required
			return nil
		}

		if err := m.BasePrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("basePrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("basePrice")
			}

			return err
		}
	}

	return nil
}

func (m *TaxItemBreakdownResponse) contextValidateOfferPrice(ctx context.Context, formats strfmt.Registry) error {

	if m.OfferPrice != nil {

		if typeutils.IsZero(m.OfferPrice) { // not required
			return nil
		}

		if err := m.OfferPrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("offerPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("offerPrice")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaxItemBreakdownResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaxItemBreakdownResponse) UnmarshalBinary(b []byte) error {
	var res TaxItemBreakdownResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
