// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// UpdateFlowStepPayload update flow step payload
//
// swagger:model UpdateFlowStepPayload
type UpdateFlowStepPayload struct {

	// display name
	// Max Length: 60
	DisplayName string `json:"displayName,omitempty"`
}

// Validate validates this update flow step payload
func (m *UpdateFlowStepPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateFlowStepPayload) validateDisplayName(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DisplayName) { // not required
		return nil
	}

	if err := validate.MaxLength("displayName", "body", m.DisplayName, 60); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update flow step payload based on context it is used
func (m *UpdateFlowStepPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateFlowStepPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateFlowStepPayload) UnmarshalBinary(b []byte) error {
	var res UpdateFlowStepPayload
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
