// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateProductPriceBandPayload update product price band payload
//
// swagger:model UpdateProductPriceBandPayload
type UpdateProductPriceBandPayload struct {

	// description
	Description string `json:"description,omitempty"`

	// display name
	// Max Length: 60
	DisplayName string `json:"displayName,omitempty"`
}

// Validate validates this update product price band payload
func (m *UpdateProductPriceBandPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateProductPriceBandPayload) validateDisplayName(formats strfmt.Registry) error {
	if swag.IsZero(m.DisplayName) { // not required
		return nil
	}

	if err := validate.MaxLength("displayName", "body", m.DisplayName, 60); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update product price band payload based on context it is used
func (m *UpdateProductPriceBandPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateProductPriceBandPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateProductPriceBandPayload) UnmarshalBinary(b []byte) error {
	var res UpdateProductPriceBandPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
